### ISSUE TITLE
[Bug] 中文字幕角标 Badge 添加逻辑

### ISSUE THREAD

**Issue by hezhiming1995** [metatube-community/jellyfin-plugin-metatube#104]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

latest

### MetaTube Server Version

latest

### What OS are you seeing the problem on?

Linux

### Description

已在配置界面设置了Badge url (包括公共图床png格式的角标，和default zimu.png)，但是在进行刮削时，未添加字幕角标到相应的主图片中。不确定是否是中文字幕角标的添加逻辑与我理解有偏差，亦或者确实是BUG？

**Comment by suede299** [comment]
计划任务时才会去添加（图标、风格词条）。如果手动添加“中文字幕”风格，就不会在封面上角标。
所以我有外挂字幕，又不想改文件名，就只能自己加上“中文字幕”风格词条，没法拥有对应的封面角标了。

**Comment by hezhiming1995** [comment]
明白您的意思了，“中文字幕”的角标添加到封面图的逻辑比较奇怪，经常出现有一些视频文件名后缀是以-C结尾的，但是没有在封面图中添加上中文字幕的角标。
可以确定的一个场景就是：如果你刮削一遍某一个视频，并且手动执行了计划任务后，添加上了“中文字幕”的角标。但是你这个时候对于刮削的内容不满意，**重新刮削了一遍，封面图的“中文字幕”的角标消失，再手动执行计划任务后，这个时候封面图并不会再添加“中文字幕”的角标。**
