### ISSUE TITLE
[Feature] metatube-server 后端程序是否可以开源？

### ISSUE THREAD

**Issue by hezhiming1995** [metatube-community/jellyfin-plugin-metatube#108]
### Description

https://github.com/metatube-community/metatube-server-releases 后端代码库中目前并未全部开源，此外构建的 releases中针对 source code.zip包下载解压也是没有具体的源码信息，是否可以对于后端内容开源处理？

**Comment by xjasonlyu** [comment]
开源的啊，源码就是sdk。
