### ISSUE TITLE
[Bug] 点击识别没有反应

### ISSUE THREAD

**Issue by sinosofti** [metatube-community/jellyfin-plugin-metatube#109]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

latest

### MetaTube Server Version

latest

### What OS are you seeing the problem on?

Windows

### Description

点击emby的修改图像 
![image](https://user-images.githubusercontent.com/38282416/209470677-be57999e-3d46-44ad-ae9b-e0b57d50c707.png)

### MetaTube Server

![image](https://user-images.githubusercontent.com/38282416/209470848-8e7d0188-c7d4-4782-926f-d5d27bf954ec.png)

### Jellyfin/Emby Logs

1

### MetaTube Server Logs

点击时的日志
![image](https://user-images.githubusercontent.com/38282416/209470681-3ca72833-f42d-480d-a045-8286f874818e.png)

### How to Reproduce
![image](https://user-images.githubusercontent.com/38282416/209470820-9712925a-c03a-42bd-af33-59817ee97668.png)

**Comment by qiuzhiaa126** [comment]
同样的问题  有办法吗？
