### ISSUE TITLE
[Bug] 在nfo信息 <![CDATA[ xxxxxxxxxx ]]> 能不能删掉

### ISSUE THREAD

**Issue by okeido8** [metatube-community/jellyfin-plugin-metatube#113]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

lasted

### MetaTube Server Version

lasted

### What OS are you seeing the problem on?

Windows

### Description

谷歌翻译nfo生成时,CDATA单词在plot和outline上生成,如果不是重要的功能的话,想知道能不能让CDATA句子不出来。 CDATA进入nfo的话,infuse软件里没有情节。 直接用编辑器删除CDATA单词,修改后使用。 拜托你了 总是谢谢你

**Comment by xjasonlyu** [comment]
不能，这是Emby/Jellyfin的行为。

**Comment by okeido8** [comment]
> 不能，这是Emby/Jellyfin的行为。

只能亲自做了。 还是很好地使用METATUBE好的插件。 节约很多时间
