### ISSUE TITLE
[Feature] javtube如何更新到metatube

### ISSUE THREAD

**Issue by whuanghong** [metatube-community/jellyfin-plugin-metatube#115]
### Description

javtube如何更新到metatube

需要手动更新，还是安装新插件

**Comment by BH2TYQ** [comment]
Hi, based on my experience you may need to uninstall javtube (Front-end and Back-end both), and re-install fully the metatube.
btw, you may find the icon of the plug-in has chaged to 'Metatube' if u had selected auto-upgrade for javtube.

**Comment by capsshift** [comment]
我是客户端重新安装了插件，服务端重新部署了。

**Comment by whuanghong** [comment]
> 
javtube彻底删除了吗
