### ISSUE TITLE
希望可以单独设置代理

### ISSUE THREAD

**Issue by Tough-JK** [metatube-community/jellyfin-plugin-metatube#116]
### Description

希望在部署后端的时候可以单独设置代理 http socks5这种

### Do you have a specific solution in mind?

新增一个代理配置参数

**Comment by Tough-JK** [comment]
> ### DescriptionDescription
> 希望在部署后端的时候可以单独设置代理 http socks5这种希望在部署后端的时候可以单独设置代理 http socks5这种
> 
> ### Is this feature related to a specific bug?Is this feature related to a specific bug?
> _No responseNo response_
> 
> ### Do you have a specific solution in mind?Do you have a specific solution in mind?
> 新增一个代理配置参数新增一个代理配置参数



> ### Description
> 希望在部署后端的时候可以单独设置代理 http socks5这种
> 
> ### Is this feature related to a specific bug?
> _No response_
> 
> ### Do you have a specific solution in mind?
> 新增一个代理配置参数



> 

我找到设置的方法了  是自己傻了

**Comment by gm-fire** [comment]
附议

**Comment by cyril-cheng** [comment]
不是一直都有吗？？？讲道理

**Comment by xjasonlyu** [comment]
> 不是一直都有吗？？？讲道理

感谢终于有人说出了大实话。

这个“单独代理”配置一直都有的，而且就在wiki里，使用环境变量配置即可。
