### ISSUE TITLE
[Feature] 提供API

### ISSUE THREAD

**Issue by jsdfhasuh** [metatube-community/jellyfin-plugin-metatube#120]
### Description

设计者，可以考虑出一个API吗，用curl向后端请求数据，不单纯限于在emby或者jellyfin上面使用

**Comment by xjasonlyu** [comment]
API本身就是提供的，具体借口参数可以直接查看后端源码。

**Comment by jsdfhasuh** [comment]
谢谢，我通过查看容器的日志，也看到接口了
