### ISSUE TITLE
[Bug] 添加字幕角标无效，之前javtube是可以的

### ISSUE THREAD

**Issue by mspzyzh** [metatube-community/jellyfin-plugin-metatube#121]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2022.1218.1400.0

### MetaTube Server Version

v1.0.25

### What OS are you seeing the problem on?

Linux

### Description

添加字幕角标无效，之前javtube是可以的

**Comment by Felix2yu** [comment]
我也有这个问题，近期的没角标

**Comment by catch6** [comment]
我的也是，没有角标

**Comment by shanyan-wcx** [comment]
+1

**Comment by mspzyzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mspzyzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mspzyzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
