### ISSUE TITLE
[Bug] 当开启翻译时，要翻译的文字中包含<符号时会导致插件报错并运行中断

### ISSUE THREAD

**Issue by catch6** [metatube-community/jellyfin-plugin-metatube#127]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2022.1218.1400.0

### MetaTube Server Version

1.0.25

### What OS are you seeing the problem on?

macOS

### Description

当开启翻译时，要翻译的文字中包含<符号时会导致插件报错并运行中断

**Comment by xjasonlyu** [comment]
有日志嘛？

**Comment by Ador-able** [comment]
> 有日志嘛？

2023-02-22 23:13:22.660 Error MetaTube.MovieProvider: Translate error: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
