### ISSUE TITLE
[Bug] wiki中「命名规范」无内容

### ISSUE THREAD

**Issue by Felix2yu** [metatube-community/jellyfin-plugin-metatube#130]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

x

### MetaTube Server Version

x

### Description

自从两个月前重命名后wiki中「命名规范」一直都是WIP。
如果没时间更新的话，能否先把之前的内容放上去？有些系列的不知道命名的规范是什么，全网都搜不到之前页面的完整清单。

**Comment by xjasonlyu** [comment]
其实源码里是有的：https://raw.githubusercontent.com/metatube-community/metatube-community.github.io/main/docs/wiki/naming-rules.md

**Comment by Felix2yu** [comment]
> 其实源码里是有的：[metatube-community/metatube-community.github.io@`main`/docs/wiki/naming-rules.md (raw)](https://raw.githubusercontent.com/metatube-community/metatube-community.github.io/main/docs/wiki/naming-rules.md)

我也有点到源码那个页面去，下面预览是WIP我也就没再点raw进去看
