### ISSUE TITLE
[Feature] 希望增加演员唯一编码识别功能

### ISSUE THREAD

**Issue by BH2TYQ** [metatube-community/jellyfin-plugin-metatube#141]
### Description

目前对于演员的识别逻辑为：番号-刮削源-演员信息；但是这样对改过名（尤其是多次改名）的演员影片整理极其不方便，一方面搜索需要以日文进行搜索，另外，遇到如下这种情况，整理影片会非常抓狂：
------------------------------
石田カレン
 别名：イザベラ, 廣瀬エレナ, 霧島レオナ 
---------------------

这个情况下，假设我已经把【石田カレン】的影片进行了整理归档并移出媒体库，这样之后就没有办法再继续搜索【廣瀬エレナ】【イザベラ】【霧島レオナ】这三个名字了，只能提前记下来；但是，有一种情况更为糟糕，就是这个演员还有其他的名字而且并未关联到任何名字中，如果可以实现唯一识别的话，整理归档会方便得多

**Comment by hwadong860** [comment]
最近搜索出的演员会有2个结果，第一个都是黑的？以至于无法正常添加演员元数据
