### ISSUE TITLE
[Bug] Jellyfin提示插件无法升级至2023.314.719.0

### ISSUE THREAD

**Issue by sakuyamaij** [metatube-community/jellyfin-plugin-metatube#147]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.217.1210.0

### MetaTube Server Version

2023.217.1210.0

### What OS are you seeing the problem on?

Linux

### Description

[manifest文件](2023.314.719.0)中显示最新版本为2023.314.719.0 
并给出下载链接 `https://github.com/metatube-community/jellyfin-plugin-metatube/releases/download/v2023.314.719.0/Jellyfin.MetaTube@v2023.314.719.0.zip`
而实际Release界面最新版本仅仅到2023.217.1210.0，上述链接并不存在  
是造成改错误的原因

**Comment by xjasonlyu** [comment]
已修复
