### ISSUE TITLE
【疑问】重复翻译

### ISSUE THREAD

**Issue by ghost** [metatube-community/jellyfin-plugin-metatube#149]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.217.1210.0

### MetaTube Server Version

2023.217.1210.0

### What OS are you seeing the problem on?

macOS

### Description

当开启翻译时，之前翻译过的视频，并保存了nfo文件。后面再导入，或者更换文件夹后会重新调用翻译接口再翻译一遍。这是emby的刮刮策略问题，还是MetaTube可以改进的地方？

**Comment by oahgnep** [comment]
MetaTube Server Version：[v1.0.26]

**Comment by xjasonlyu** [comment]
确实就是这么设计的。
