### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by ITtest1** [metatube-community/jellyfin-plugin-metatube#150]
### Description

當這個插件刮不到番號就亂刮，現在我決定把這些亂刮的整理成使用截圖，和使用文件名，結果不管我怎麼刪除舊的nfo並且關閉了metatube，它一樣會刮回之前的nfo資料。文件的番號根本不是nfo裡的番號，我就想要用回文件名的正確番號，可惡的是不停不停恢復成錯誤的nfo

**Comment by xjasonlyu** [comment]
一般来说正常的番号都是能搜索到的，如果是一些冷门的影片建议单独使用一个Library来存放。例如，专门创建一个媒体库存放“写真”类影片，这样可以使用自己的nfo信息而不用担心被插件覆盖。
