### ISSUE TITLE
[Bug] 大家OpenAI翻译好用吗？

### ISSUE THREAD

**Issue by eUnisk** [metatube-community/jellyfin-plugin-metatube#152]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.326.630.0

### MetaTube Server Version

1.0.27

### Description

OpenAI翻译似乎没有效果（已经填入了API Key），更换了引擎以后刷新元数据，变成了日文。是否有OpenAI版本的限制，比如收费版？

**Comment by eUnisk** [comment]
明白了，只有API Key是不够的，要有credit，我的free trail里没有credit。

**Comment by smallst** [comment]
请问什么意思？填入openai 的 api key 不能用翻译？

**Comment by eUnisk** [comment]
要有credit才行
