### ISSUE TITLE
[Feature] 后缀为-U -UC 希望可以增加角标识别

### ISSUE THREAD

**Issue by Hazard804** [metatube-community/jellyfin-plugin-metatube#158]
### Description

另外许多后缀-UC影片Metatube无法识别，不知道是否能够改善？
十分感谢！

**Comment by xjasonlyu** [comment]
已添加：https://github.com/metatube-community/jellyfin-plugin-metatube/commit/d1df2ab2cc3d11200da70ecda9945ba8217c2367 等下次更新就好了。
