### ISSUE TITLE
[Feature] Actress name in english letters

### ISSUE THREAD

**Issue by trngkn** [metatube-community/jellyfin-plugin-metatube#162]
### Description

Actress name in english letters

### Is this feature related to a specific bug?

no

### Do you have a specific solution in mind?

just have an idea, sr about my english

**Comment by yourbest** [comment]
tha's it  what i needed !

**Comment by trngkn** [comment]
> that's it what i needed !

i know how u feel, bro :v

**Comment by trngkn** [comment]
please update this feature :(
