### ISSUE TITLE
[Feature] 希望能增加对并发请求数的限制

### ISSUE THREAD

**Issue by KomikadoYUC** [metatube-community/jellyfin-plugin-metatube#164]
### Description

我是从其他插件转用jellyfin和metatube的，这就导致jellyfin能找到nfo里的影片文字信息，但找不到海报，试了一下重新刮削，结果要么会触发FANZA之类网站的请求数限制，要么触发免费后端设下的请求数限制。。如果有从插件或者服务器对请求数进行限制，对大量影片慢慢刮削的设计就好了

**Comment by zijiren233** [comment]
免费后端有10秒125次请求的限制，超过限制会拉黑IP，不过现在已经删除此限制，并删除黑名单了
