### ISSUE TITLE
希望能支持emby4.7.11版本[Feature] 

### ISSUE THREAD

**Issue by HeroicPhoenix** [metatube-community/jellyfin-plugin-metatube#169]
### Description

希望能支持emby4.7.11版本

**Comment by iovejieba** [comment]
不是支持4711么？

**Comment by Jiang-Xinyu** [comment]
> 不是支持4711么？

但是，我的4.7.11.0版本不支持啊，在群晖上安装的emby版本7.2的

**Comment by iovejieba** [comment]
具体看emby版本号  我确定4711 是支持的

**Comment by xjasonlyu** [comment]
4.7.11肯定是支持的。

**Comment by iovejieba** [comment]
如果有4.7.11 无法搜刮的问题您应该优先考虑后端 地址是否设置有误...

**Comment by Jiang-Xinyu** [comment]
> 不是支持4711么？

实际上是4.7.11 插件里面看不到

**Comment by iovejieba** [comment]
手动安装 考虑丢进去之后的权限问题 0644....给777  看不到的
