### ISSUE TITLE
[Feature] AVBASE还是无法刮削

### ISSUE THREAD

**Issue by ddddalex** [metatube-community/jellyfin-plugin-metatube#170]
### Description

用的最新EMBY4.7.11，最新的插件版本，能正常刮削，但是以前能看到AVwiki的刮削源数据出不来了。

**Comment by Dissyu** [comment]
因為舊的nfo還是用avwiki的網址開啟，要手動將舊的nfo改一下網址，或是刪掉nfo重新刮削
