### ISSUE TITLE
无法识别UC后缀[Bug] 

### ISSUE THREAD

**Issue by 1078534641** [metatube-community/jellyfin-plugin-metatube#173]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.503.910.0

### MetaTube Server Version

emby开心版

### What OS are you seeing the problem on?

Linux

### Description

识别带-uc后缀的影片，错误率很大，基本都要靠手动刮削

**Comment by LNai** [comment]
是的，现在很多AI破解中字的都带UC后缀，建议更新插件
