### ISSUE TITLE
不知道metatube的演员数据库削刮的是否为xslist[Feature] 

### ISSUE THREAD

**Issue by maxererer** [metatube-community/jellyfin-plugin-metatube#175]
### Description

出生: 2000年02月11日
三围: B94 / W59 / H87
罩杯: H Cup
出道日期: 2022年09月
星座: Aquarius
血型: n/a
身高: 155cm
国籍: 日本

XSLIST对于演员信息削刮的更全，更加完整，能否后期考虑对演员数据库有所改进，谢谢

**Comment by xjasonlyu** [comment]
是的，但是xslist加了cf盾已经没法用了。
