### ISSUE TITLE
后端日志报错 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by QZQ-QSQ** [metatube-community/jellyfin-plugin-metatube#204]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.503.910.0

### MetaTube Server Version

最新版本

### What OS are you seeing the problem on?

Windows

### Description

使用openwrt安装的后端，日志报错 runtime error: invalid memory address or nil pointer dereference

### MetaTube Server

后端日志报错 runtime error: invalid memory address or nil pointer dereference

### Jellyfin/Emby Logs

没发现logs有报错，但是不能削刮

### MetaTube Server Logs

stderr: 
stderr: 
stderr: [31m2023/09/10 21:40:33 [Recovery] 2023/09/10 - 21:40:33 panic recovered:
stderr: runtime error: invalid memory address or nil pointer dereference
stderr: runtime/panic.go:260 (0x44b67c)
stderr: runtime/signal_unix.go:837 (0x44b64c)
stderr: github.com/metatube-community/metatube-sdk-go/translate/google_free.go:24 (0xf95171)
stderr: github.com/metatube-community/metatube-sdk-go/route/translate.go:61 (0xf98315)
stderr: github.com/gin-gonic/gin@v1.9.0/context.go:174 (0xf964fc)
stderr: github.com/metatube-community/metatube-sdk-go/route/redirect.go:59 (0xf962bf)
stderr: github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x924861)
stderr: github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x92484c)
stderr: github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x923986)
stderr: github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x923969)
stderr: github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x922a0a)
stderr: github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x922691)
stderr: github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x9221bc)
stderr: net/http/server.go:2936 (0x6e0c95)
stderr: net/http/server.go:1995 (0x6dc1b1)
stderr: runtime/asm_amd64.s:1598 (0x467520)

**Comment by QZQ-QSQ** [comment]
大佬，我补充一些信息。
 1--  emby是在官方下载的embyserver-win-x64-4.7.14.0绿色版。
 2-- 操作系统windows 10 最新正式版。
 3-- 使用以下命令在openwrt x86的路由器上安装的docker（其他docker都能正常运行）。

docker run -d \
-p 8080:8080 \
-v /opt/metatube/config:/metatube/config \ 
-e TZ=Asia/Shanghai \
--name metatube \
metatube/metatube-server:latest \
-dsn metatube/config/metatube.db

     如上，右边的文件映射路径，需要加上metatube，docker才能跑起来，不然就跑不起来。
不知道上面的反馈的报错是不是加了/metatube的原因。

**Comment by xjasonlyu** [comment]
Fixed in https://github.com/metatube-community/metatube-sdk-go/commit/0312fa293a4c2322089008c45de3cae01ed6c202
