### ISSUE TITLE
[Bug] 服务端有返回数据但Jellyfin里看不到任何刮削出的资料

### ISSUE THREAD

**Issue by LegendAdmin** [metatube-community/jellyfin-plugin-metatube#208]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.503.910.0

### MetaTube Server Version

1.1.0

### What OS are you seeing the problem on?

Docker(in Zspace NAS)

### Description

Jellyfin加或不加代理也没用，服务器用公共的或者自建也都没用
自建服务器能在db文件里能查到刮削的影片描述和图片的链接什么的，但是Jellyfin端什么都不显示

### Jellyfin/Emby Logs

2023/9/22 7:40:26  System.Exception: API request error: 400 (Key: 'searchQuery.Q' Error:Field validation for 'Q' failed on the 'required' tag)
2023/9/22 7:44:40  System.Exception: API request error: 404 (Not Found)

### MetaTube Server Logs

2023/9/22 7:51:41  [GIN] 2023/09/21 - 23:51:41 | 404 |      50.986µs |      172.17.0.1 | GET      "/v1/movies?lazy=True"
2023/9/22 7:51:41  [GIN] 2023/09/21 - 23:51:41 | 200 | 18.850710702s |      172.17.0.1 | GET      "/v1/movies/search?q=1PONDO-010520_955-FHD&provider=&fallback=True"
2023/9/22 7:51:41  [1.013ms] [rows:1] SELECT * FROM \`movie_metadata\` WHERE number = "010520_955" COLLATE NOCASE OR id = "010520_955" COLLATE NOCASE
2023/9/22 7:51:41  [GORM] 2023/09/21 23:51:41 github.com/metatube-community/metatube-sdk-go/engine/movie.go:24
2023/9/22 7:51:22  [3.667ms] [rows:1] SELECT * FROM \`movie_metadata\` WHERE provider = "1Pondo" AND id = "010520_955" COLLATE NOCASE ORDER BY \`movie_metadata\`.\`id\` LIMIT 1
2023/9/22 7:51:22  [GORM] 2023/09/21 23:51:22 github.com/metatube-community/metatube-sdk-go/engine/movie.go:173

**Comment by LegendAdmin** [comment]
在 #140 找到问题原因了，是因为开启了 `Movie provider filter`但是没填内容

**Comment by zhshp2008** [comment]
感谢这个帖子，我也受这个问题困扰了很久……
