### ISSUE TITLE
javbus [Bug] 

### ISSUE THREAD

**Issue by cxhgit123** [metatube-community/jellyfin-plugin-metatube#211]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.503.910.0

### MetaTube Server Version

1.0.28

### Description

javbus 好像没有用我用javbus网页查询到了但插件没结果

**Comment by xjasonlyu** [comment]
bus更新了，现在需要登录了才行。

**Comment by cxhgit123** [comment]
那要怎么适配

**Comment by xjasonlyu** [comment]
Fixed by https://github.com/metatube-community/metatube-sdk-go/commit/0b047c3d0495983ea8d8ae47fcd6e2142cf01673
