### ISSUE TITLE
[Feature] 自定义openai api的url

### ISSUE THREAD

**Issue by lisankai93** [metatube-community/jellyfin-plugin-metatube#212]
### Description

查了issue有类似的问题，现在pandora 的fk 模拟api基本可以算是免费用了，api url地址是https://ai.fakeopen.com
也支持自己反代，因此希望项目可以支持自定义url 

谢谢！

### Is this feature related to a specific bug?

不是

### Do you have a specific solution in mind?

是的

**Comment by xjasonlyu** [comment]
cc @zijiren233
