### ISSUE TITLE
[Bug] AVBASE刮削到的id有 ： ，导致redirect无法正确获取id

### ISSUE THREAD

**Issue by Ador-able** [metatube-community/jellyfin-plugin-metatube#229]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

最新

### MetaTube Server Version

最新

### Description

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/17660606/e1ef2432-a518-48be-9824-cb483cec6b00)

这个位置遇到id中带有：的无法正确识别。AVBASE刮削到的都有：

**Comment by Topbcy** [comment]
我之前提過這個BUG，然後就沒有然後了 .....

https://github.com/metatube-community/jellyfin-plugin-metatube/issues/214#issuecomment-1762663885

**Comment by xjasonlyu** [comment]
后端这个问题修过了，这个问题在Emby上是没有的，Jellyfin还没时间去看

**Comment by Ador-able** [comment]
我这边用的emby。问题是存在的

**Comment by xjasonlyu** [comment]
> 我这边用的emby。问题是存在的

后端更新之后，avbase的重新刮一遍，应该没问题了吧，之前测试都是好的
