### ISSUE TITLE
[Bug] 在元数据下载器添加TheMovieDB后，匹配电影会强制匹配一个MetaYube的源

### ISSUE THREAD

**Issue by chimiansw** [metatube-community/jellyfin-plugin-metatube#230]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.1013.2110.0

### MetaTube Server Version

"version": "1.1.4"

### What OS are you seeing the problem on?

Other

### Description

我可能比较个性，把一些R级片比如艾玛马克斯之类的可以在TheMovieDb找到数据的电影放到小电影一起了，所以增加了一个TheMovieDB的元数据下载器，但是这个在选择TheMovieDB的元数据后，会强制匹配一个MetaTube的数据，图片也会优先选择MetaTube的结果，希望可以修复这个bug

![1699950086064](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/52277562/77452f4a-8142-43d6-9247-b4887ca1df10)
![1699950112386](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/52277562/412773cd-2329-4178-ae52-d067bb9816ff)

### How to Reproduce

添加TheMovieDB下载器后，在TheMovieDB 电影ID中搜索330683（这是The Submission of Emma Marx: Boundaries），并选择TheMovieDB的结果且勾选替换图片后，会变成MetaTube 电影 Id：DUGA:dahlia-0055相关的图片及信息

**Comment by chimiansw** [comment]
通过尝试我发现把元数据和图片的TheMovieDB的下载器都排到最前，可以避免图片和文字不匹配，但是MetaTube 电影 Id仍然会强制匹配一个数据

**Comment by zhayo0** [comment]
我也有同一个问题，导致metatube不停刮削电影里的人物名字。每天日志好几万

**Comment by abc2001x** [comment]
我也有类似的问题, 其实就是检索不出结果, 然后用了duga.jp 推荐的结果. 导致很多老v封面都是同一个

**Comment by abc2001x** [comment]
> 我也有类似的问题, 其实就是检索不出结果, 然后用了duga.jp 推荐的结果. 导致很多老v封面都是同一个

所以我把DUGA去掉了,不然老给错的结果.估计是爬取页面取错数据了,把页面的推荐结果给爬进来了

**Comment by xiaohezao** [comment]
duga的锅，这个刮削源匹配宽容度不知道怎么的宽容度非常大，我一些pornhub下载的片子根本没有番号信息它也会强制从duga刮削一个给我。暂时的解决办法是在插件设置里movie provider filter写入Getchu,AVWIKI,AIRAV,ARZON,JAV321,FANZA,Caribbeancom,FC2,Pcolle,1Pondo,10musume,KIN8,C0930,H0930,H4610,MYWIFE,MGS,XXX-AV,Gcolle,PACOPACOMAMA,MURAMURA,HeyDouga,HEYZO,CaribbeancomPR,PRESTIGE,SOD,AVE,TOKYO-HOT,JavBus,DLsite

刮削源优先级从左往右，可以把一些不用的去掉，不要把duga写进去

**Comment by zhayo0** [comment]
> duga的锅，这个刮削源匹配宽容度不知道怎么的非常大，我一些pornhub下载的片子根本没有番号信息它也会强制从duga刮削一个给我。暂时的解决办法是在插件设置里movie provider filter写入Getchu,AVWIKI,AIRAV,ARZON,JAV321,FANZA,Caribbeancom,FC2,Pcolle,1Pondo,10musume,KIN8,C0930,H0930,H4610,MYWIFE,MGS,XXX-AV,Gcolle,PACOPACOMAMA,MURAMURA,HeyDouga,HEYZO,CaribbeancomPR,PRESTIGE,SOD,AVE,TOKYO-HOT,JavBus,DLsite
> 
> 刮削源优先级从左往右，可以把一些不用的去掉，不要把duga写进去

但是我后台没有duga设置过呀

**Comment by chimiansw** [comment]
> duga的锅，这个刮削源匹配宽容度不知道怎么的非常大，我一些pornhub下载的片子根本没有番号信息它也会强制从duga刮削一个给我。暂时的解决办法是在插件设置里movie provider filter写入Getchu,AVWIKI,AIRAV,ARZON,JAV321,FANZA,Caribbeancom,FC2,Pcolle,1Pondo,10musume,KIN8,C0930,H0930,H4610,MYWIFE,MGS,XXX-AV,Gcolle,PACOPACOMAMA,MURAMURA,HeyDouga,HEYZO,CaribbeancomPR,PRESTIGE,SOD,AVE,TOKYO-HOT,JavBus,DLsite
> 
> 刮削源优先级从左往右，可以把一些不用的去掉，不要把duga写进去

感谢，我试试
