### ISSUE TITLE
[Feature] 能否设定按钮把刮削来的海报和封面自动保存到视频所属的文件夹而非特别开一个新的存储地点？

### ISSUE THREAD

**Issue by Abibabodudu** [metatube-community/jellyfin-plugin-metatube#244]
### Description

如题能否把文件存储在本视频文件夹内

而非单独开新的文件夹，方便阅览观看？

同时可以和infuse联动！！！感谢大佬垂青~

**Comment by noir1216** [comment]
这功能不是emby自带的？

**Comment by Abibabodudu** [comment]
> 这功能不是emby自带的？

啊啊这样的吗老哥具体在哪里啊没找到这个案件欸，我纯小白，再回去翻一翻，谢谢老哥！！

**Comment by noir1216** [comment]
> > 这功能不是emby自带的？
> 
> 啊啊这样的吗老哥具体在哪里啊没找到这个案件欸，我纯小白，再回去翻一翻，谢谢老哥！！

直接在媒体库里设置
![QQ截图20231212123329](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/7a3ad017-cd8d-449b-8621-39e40fa497c7)

**Comment by Abibabodudu** [comment]
> > > 这功能不是emby自带的？
> > 
> > 
> > 啊啊这样的吗老哥具体在哪里啊没找到这个案件欸，我纯小白，再回去翻一翻，谢谢老哥！！
> 
> 直接在媒体库里设置 ![QQ截图20231212123329](https://private-user-images.githubusercontent.com/44556349/289745290-7a3ad017-cd8d-449b-8621-39e40fa497c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTk4NTcsIm5iZiI6MTcwMjM1OTU1NywicGF0aCI6Ii80NDU1NjM0OS8yODk3NDUyOTAtN2EzYWQwMTctY2Q4ZC00NDliLTg2MjEtMzllNDBmYTQ5N2M3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA1MzkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZGQwZmE1ZjRmMThhNWRmZGM2YjU3ODY2ZGNiODc4NjMxNGJkMmNjODU5MGRlZmE0MjhmMWU0MmQwODFjNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-A2gEd2M66l2uLxfga5OB9-snRcgiE3ldz7g3GokpuY)

谢谢老哥！！我这里确保是打开的，

但是图像并不在我的视频文件夹而是统一的Emby文件夹，

或许是我个人的问题吧！！我再查看一下如果之后有任何问题再反馈给大家！！

感谢老哥的耐心解惑

小白感激不尽！！！
