### ISSUE TITLE
[Bug] 会刮削普通电影的人物,导致日志很多,而且挤占正常刮削进程

### ISSUE THREAD

**Issue by zhayo0** [metatube-community/jellyfin-plugin-metatube#249]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

最新

### MetaTube Server Version

最新

### What OS are you seeing the problem on?

Linux

### Description

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/49388625/71e3870b-b127-4c16-b85f-5cfcbede36f6)
会正常电影的演员元数据刮削中出现metatube.
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/49388625/54c8818b-cbf8-46dc-92e5-c3955af0a633)
这是后台数据

### MetaTube Server

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/49388625/0cc99e51-e306-4ac9-aec7-1f7c275ef019)
后台配置

### Jellyfin/Emby Logs

<html>
<body>

[0.228ms] [rows:0] SELECT * FROM `actor_metadata` WHERE provider = "XsList" AND name = "Matt Wilson" COLLATE NOCASE
--

<br class="Apple-interchange-newline">
</body>
</html>

### MetaTube Server Logs

<html>
<body>

[0.228ms] [rows:0] SELECT * FROM `actor_metadata` WHERE provider = "XsList" AND name = "Matt Wilson" COLLATE NOCASE
--

<br class="Apple-interchange-newline">
</body>
</html>

### How to Reproduce

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/49388625/a825a4d4-6744-4cb0-be69-b20b8e24fa01)
正常电影的刮削器没有勾选metatube

**Comment by luckyxyz1981** [comment]
我也发现该问题，在媒体库中，比如“电影A”，“电影B”，“电影A”中没有启用metatube，只选用了TMDB，“电影B”启用metatube，当“电压A”搜索演员时，依然会调用metatube搜索演员信息
