### ISSUE TITLE
[Bug] jellyfin可以刮削到正確資料，但是emby卻不可以。

### ISSUE THREAD

**Issue by ITtest1** [metatube-community/jellyfin-plugin-metatube#251]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.1215.2200.0

### MetaTube Server Version

Ubuntu

### What OS are you seeing the problem on?

Linux

### Description

你可以在emby和jellyfin，分別手動刮削ka-1904，復現錯誤

### How to Reproduce

手動刮削ka-1904

**Comment by xjasonlyu** [comment]
你手动识别 ka-1904# 就好了，wiki FAQ里有写。

**Comment by ITtest1** [comment]
> 你手动识别 ka-1904# 就好了，wiki FAQ里有写。

手動識別出兩種不一樣的結果

**Comment by xjasonlyu** [comment]
在数字后面加个 # 就好了

**Comment by ITtest1** [comment]
> 在数字后面加个 # 就好了

加#就行了
