### ISSUE TITLE
[Feature] 能否自定义自动刮削顺序或优先级

### ISSUE THREAD

**Issue by RYnuo** [metatube-community/jellyfin-plugin-metatube#255]
### Description

自动刷新元数据时会选择默认搜索到的第一个数据，手动识别就可以正常调用刮削过滤设置的内容显示对应数据。

能否让选择的搜索数据采用刮削过滤里面的设置内容，按设置的优先级或对应名称选择数据内容？

或者能否开放一个设置位，专门设置刷新元数据的搜索优先级或过滤功能？

**Comment by xjasonlyu** [comment]
参见 provider filter

**Comment by RYnuo** [comment]
provider filter 试过的，无法在自动刷新元数据时调用provider filter设置的关键字。比如我设置

**Comment by SunneeYang** [comment]
provider filter只是筛选抓取的结果，抓取还是所有 provider 都去抓，可以设置 metatubeid，指定 provider
