### ISSUE TITLE
[Feature] 适配4.8.0.65

### ISSUE THREAD

**Issue by DDDDDDaniel** [metatube-community/jellyfin-plugin-metatube#258]
### Description

因为自己手贱emby无法降级了，想问问大概什么时候能适配4.8.0.65版本

**Comment by copurxia** [comment]
应该要等到4.8正式版了

**Comment by copurxia** [comment]
嗯，正式版来了

**Comment by wangke8023** [comment]
> 嗯，正式版来了

最新的还是 4.8.0.80bate版啊

**Comment by copurxia** [comment]
> > 嗯，正式版来了
> 
> 最新的还是 4.8.0.80bate版啊

4.8.0.80是正式版啊

**Comment by copurxia** [comment]
> > 嗯，正式版来了
> 
> 最新的还是 4.8.0.80bate版啊

We're excited to announce that Emby 4.8 stable release is going live right now! All packages are being updated and will be ready to download soon.

**Comment by wangke8023** [comment]
4.8.0.80bate版  无法适配，点击保存无法成功

**Comment by copurxia** [comment]
> 4.8.0.80bate版 无法适配，点击保存无法成功

是的，我的意思是，开发者说过不适配beta，所以等正式版适配了
曲线救国的话，可以在客户端操作，客户端是能保存的

**Comment by wangke8023** [comment]
> > > 嗯，正式版来了
> > 
> > 
> > 最新的还是 4.8.0.80bate版啊
> 
> 4.8.0.80是正式版啊

呃呃 刚去官方看了一下，确实是正式版，只是我用的何先生的版本，标注的是bate，不好意思

**Comment by xjasonlyu** [comment]
会修复的，别急。

**Comment by copurxia** [comment]
辛苦了辛苦了，虽然我感觉更像是emby那边的锅？

> 会修复的，别急。

**Comment by xjasonlyu** [comment]
是 Emby 的问题，他们更新了配置页面 JS 一些东西，所以插件端也得跟着适配一下了。

**Comment by wangke8023** [comment]
> 是 Emby 的问题，他们更新了配置页面 JS 一些东西，所以插件端也得跟着适配一下了。

辛苦大佬！emby也是蛋疼，一个抽象的插件集成平台的代码还能一个小版本都不让已经上架的插件不兼容，无法正常运行，难以理解

**Comment by conversun** [comment]
> 会修复的，别急。

很棒，已赞助😀
