### ISSUE TITLE
[Bug] 修改海报图片后添加中文角标会变回原来的海报图片

### ISSUE THREAD

**Issue by shanyan-wcx** [metatube-community/jellyfin-plugin-metatube#261]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

latest

### Description

修改海报图片后添加中文角标会变回原来的海报图片

**Comment by xjasonlyu** [comment]
浏览器有缓存就会这样，已知bug没有特别好的解决办法。

**Comment by noir1216** [comment]
> 浏览器有缓存就会这样，已知bug没有特别好的解决办法。

我清除了浏览器缓存，然后删除了插件，再关闭emby，然后重新安装，勾选了badges，设置好链接。再重新扫元数据。也都还是没中文角标。
