### ISSUE TITLE
突然搜不出来任何内容

### ISSUE THREAD

**Issue by Sostay** [metatube-community/jellyfin-plugin-metatube#262]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

2023.1215.2200.0

### What OS are you seeing the problem on?

Windows

### Description

之前一直正常使用的，最近突然搜不出来任何结果

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/6897274/71d91f86-7bcc-4ae4-9e6a-163a35ebd4f6)

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/6897274/5c054186-ab2b-4ea6-adc9-00529483b21a)

**Comment by zyyy132** [comment]
一样，jellyfin和plex都不行

**Comment by Sostay** [comment]
虽然我也不太理解没有计划修复是啥意思。。但是有人知道这个是啥原因导致的吗？求不吝指教……

**Comment by Sostay** [comment]
免费后端失效了，自己部署了……
