### ISSUE TITLE
[Bug] 不识别docker 代理

### ISSUE THREAD

**Issue by vmnet** [metatube-community/jellyfin-plugin-metatube#268]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.1215.2200.0

### MetaTube Server Version

1.2.1

### What OS are you seeing the problem on?

Other

### Description

进入docker 里用curl测试docder代理是正常的，也能收到 jellyfin 端的请求所用docker 代理格式
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "socks5h://10.0.0.80:20170",
     "httpsProxy": "socks5h://10.0.0.80:20170",
     "noProxy": "*.centernet.int,*.contoso.int,10.0.0.0/24"
   }
 }
}

又换了个机器改用下面docker代理配置可以采集到meta了

{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://10.0.0.80:20171",
     "httpsProxy": "http://10.0.0.80:20171",
     "noProxy": "*.centernet.int,*.contoso.int,10.0.0.0/24"
   }
 }
}

可能是metatube 不支持这种socks5h:// 代理格式

### MetaTube Server Logs

进入docker里装了tcpdump监控
`01:49:04.837294 IP 10.0.0.20.42986 > 172.17.0.2.8080: Flags [P.], seq 1:235, ack 1, win 260, options [nop,nop,TS val 2381464733 ecr 3984266734], length 234: HTTP: GET /v1/movies/search?q=FC2-PPV-4196201&provider=&fallback=True HTTP/1.1`

`01:49:04.846841 IP 172.17.0.2.51370 > 10.0.0.80.53: 8431+ [1au] AAAA? socks5h. (36)
01:49:04.846959 IP 172.17.0.2.37921 > 10.0.0.80.53: 58273+ [1au] A? socks5h. (36)`

**Comment by xjasonlyu** [comment]
参考：https://metatube-community.github.io/wiki/proxy-configuration/

应该是不支持 `socks5h`，用 `socks5` 应该就行了。

**Comment by vmnet** [comment]
> 参考：https://metatube-community.github.io/wiki/proxy-configuration/
> 
> 应该是不支持 `socks5h`，用 `socks5` 应该就行了。

是我过于马虎了，我一直用socks5h://这种，其它的docker 应用没出过问题，所以倒腾了好几个小时也没头绪，最后才想到可能代理格式不识别的问题
