### ISSUE TITLE
[Bug] arzon促销导致刮削标题错误

### ISSUE THREAD

**Issue by KuanKan410** [metatube-community/jellyfin-plugin-metatube#269]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

01f2c1ef7269

### What OS are you seeing the problem on?

Linux

### Description

最近是arzon的促销季节，刮削出来的部分促销影片的标题都带上了【歳末新春】的字样，导致刮削出来的标题名都出现了错误

**Comment by dewe001** [comment]
请问如何解决的？又出现了新的促销字样

**Comment by KuanKan410** [comment]
> 请问如何解决的？又出现了新的促销字样

在设置->Substitution下，其中的Title substitution table与Genre substitution table内填写
`【歳末新春】=
【AV大好き】=`
这是目前我找到的标题替换的方法，把广告词用空白替换掉，但是副标题因为是爬取了其原始数据并且无法使用表达式，所以目前我没有找到方法
