### ISSUE TITLE
[Bug] jetllyfin安装插件失败

### ISSUE THREAD

**Issue by OaimIsGnay** [metatube-community/jellyfin-plugin-metatube#272]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215

### MetaTube Server Version

2023.1215

### What OS are you seeing the problem on?

Other

### Description

[Bug] jetllyfin安装插件失败

**Comment by hahaha4678** [comment]
j黑群晖ellyfin 内添加订阅地址，内部源可以搜索到插件，外部源搜索不到，另外内部源安装失败，魔法也给了，但是就是不行。哪出毛病了

**Comment by OaimIsGnay** [comment]
> j黑群晖ellyfin 内添加订阅地址，内部源可以搜索到插件，外部源搜索不到，另外内部源安装失败，魔法也给了，但是就是不行。哪出毛病了

你说的内部源是啥。。是cdn的那个吗
