### ISSUE TITLE
[Bug] 使用https://metatube.pyhdxy.com刮削不出数据了

### ISSUE THREAD

**Issue by liuzj288** [metatube-community/jellyfin-plugin-metatube#273]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

1.2.1

### Description

![5d6887f6a530a9f4067691b3002bc438](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/13833404/c31750bd-a4ff-4ec5-9b51-494009be81d7)

**Comment by OaimIsGnay** [comment]
请问插件你是咋安装的。求指教

**Comment by linsong-cn** [comment]
不是BUG，作者在文档里解释了——“由于使用人数过多，而免费后端服务器由于成本因素有时会疏于维护导致图片无法加载或者刮削失败等问题，现暂时下线免费后端服务。建议自行搭建后端仍为主。”

**Comment by OaimIsGnay** [comment]
> 不是BUG，作者在文档里解释了——“由于使用人数过多，而免费后端服务器由于成本因素有时会疏于维护导致图片无法加载或者刮削失败等问题，现暂时下线免费后端服务。建议自行搭建后端仍为主。”

我目前知道三个免费的后端，但是好像都不行了，请问如何自己搭建后端啊

**Comment by linsong-cn** [comment]
> > 不是BUG，作者在文档里解释了——“由于使用人数过多，而免费后端服务器由于成本因素有时会疏于维护导致图片无法加载或者刮削失败等问题，现暂时下线免费后端服务。建议自行搭建后端仍为主。”
> 
> 我目前知道三个免费的后端，但是好像都不行了，请问如何自己搭建后端啊

参考[这里](https://metatube-community.github.io/wiki/server-deployment/)

**Comment by OaimIsGnay** [comment]
> > > 不是BUG，作者在文档里解释了——“由于使用人数过多，而免费后端服务器由于成本因素有时会疏于维护导致图片无法加载或者刮削失败等问题，现暂时下线免费后端服务。建议自行搭建后端仍为主。”
> > 
> > 
> > 我目前知道三个免费的后端，但是好像都不行了，请问如何自己搭建后端啊
> 
> 参考[这里](https://metatube-community.github.io/wiki/server-deployment/)

谢谢大佬了。好像还需要魔法，有点不好搞。。。有点复杂
