### ISSUE TITLE
保存应用是页面会刷新导致保存不成功

### ISSUE THREAD

**Issue by cxhgit123** [metatube-community/jellyfin-plugin-metatube#280]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

1.2.2

### Description

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/50816484/94c347a8-a564-4019-828b-ed404dc57852)
这个版本插件配置完点保存会自动刷新页面导致配置失败请大佬解决下

### MetaTube Server

2023.1215.2200.0

**Comment by xjasonlyu** [comment]
已适配
