### ISSUE TITLE
[Feature] 翻译功能增加 OpenAI 的提示词选项

### ISSUE THREAD

**Issue by conversun** [metatube-community/jellyfin-plugin-metatube#281]
### Description

让用户自己设置提示词, 参考 https://github.com/L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN 可能可以绕过限制
<img width="1165" alt="截屏2024-02-05 15 08 01" src="https://github.com/metatube-community/jellyfin-plugin-metatube/assets/22893221/1353175e-d1f2-424c-8cb6-ddc5022274c8">

**Comment by WengTzu** [comment]
在網頁上測試，簡單使用"請以XX代替敏感字詞"，就可以成功翻譯出title
希望可以整合到metatube中
