### ISSUE TITLE
[Bug]  OpenAI 无法翻译

### ISSUE THREAD

**Issue by dealex63** [metatube-community/jellyfin-plugin-metatube#284]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2024.205.435.0

### MetaTube Server Version

1.2.2

### What OS are you seeing the problem on?

Docker

### Description

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/34654522/ec1f34b3-afe3-4c1d-a276-0aaf2b95ce95)
麻煩大佬看看

**Comment by conversun** [comment]
#281
