### ISSUE TITLE
[Bug] 2024.205.435 在4.8.0.80 上还是无法使用

### ISSUE THREAD

**Issue by CoderYiXin** [metatube-community/jellyfin-plugin-metatube#286]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.205.435

### MetaTube Server Version

v1.2.2

### Description

插件设置点不开，无法搜刮信息，不向服务器调用！

**Comment by xuecunqwer** [comment]
4.9.0测试版无法设置插件无法使用

**Comment by Melody-Test** [comment]
一样的问题 插件拖进文件夹控制台什么都不显示 升级之前正常

**Comment by xjasonlyu** [comment]
> 一样的问题 插件拖进文件夹控制台什么都不显示 升级之前正常 同样的版本

看一眼权限问题，以及升级的版本是否一致。

**Comment by xuecunqwer** [comment]
> > 一样的问题 插件拖进文件夹控制台什么都不显示 升级之前正常 同样的版本
> 
> 看一眼权限问题，以及升级的版本是否一致。

应该怎么搞呢

**Comment by CoderYiXin** [comment]
> > 一样的问题 插件拖进文件夹控制台什么都不显示 升级之前正常 同样的版本
> 
> 看一眼权限问题，以及升级的版本是否一致。

版本一致，权限无问题！

**Comment by noir1216** [comment]
我的正常，能进设置，也能削刮
![22](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/88fcec0f-9565-4148-9e0b-eb96eb81cc13)
![33](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/c1e63c49-92fe-425e-bea2-b96b1af02c44)
