### ISSUE TITLE
[Bug] 演员头像无法选择的问题

### ISSUE THREAD

**Issue by ForestL18** [metatube-community/jellyfin-plugin-metatube#288]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.205.435

### MetaTube Server Version

1.2.2

### What OS are you seeing the problem on?

Linux

### Description

2024.205.435 在4.8.1.0版本的emby上，刮削数据时可以刮削到演员头像，但无法使用`修改图像`功能来选择同一演员的其他头像。
使用修改图像功能时，点进去是一片空白，什么也没有加载。

修改图像的选项
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/45709305/7d9dd27e-d83e-4451-be14-ad3d52025f51)

点进去一片空白
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/45709305/4b94e34e-6a8b-4833-a463-77a6a1145c43)

**Comment by noir1216** [comment]
是不是你勾选了Movie provider filter。然后你指定的那些搜索源里刚好没有这位老师的头像。
w我就是指定了Movie provider filter，有的老师头像选不了。只有取消勾选Movie provider filter或者受到添加
![222](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/44556349/04630f03-cf5a-4795-8ad8-de7ffeeba1d5)

**Comment by noir1216** [comment]
> > 点开女优信息编辑界面，看看MetaTube ld那一行是不是空的，是的话就加上GFriends:女优名字，然后你就能选取女优头像了。如下图： ![xxx](https://private-user-images.githubusercontent.com/44556349/303904882-314b9a13-85e3-42d7-8246-fa7e74133036.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MzkxMjEsIm5iZiI6MTcwNzYzODgyMSwicGF0aCI6Ii80NDU1NjM0OS8zMDM5MDQ4ODItMzE0YjlhMTMtODVlMy00MmQ3LTgyNDYtZmE3ZTc0MTMzMDM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA4MDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzI3MGJjMzgxNWE1NzU5MDg3MDMwNDRjMTI2ZmRkZjA4YjE4MTdmNzk3Nzk3OTdiNjVlNzY1NTM0ZTQ5NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rdPYqZWTUXGJShs3oNBbsUozguR3b_fFP72E7udRPnY)
> 
> 还真是，这是插件的问题吗？没有自动写入metatube ID的信息，手动一个个输入也太麻烦了🥴

不清楚，我的正常，基本都有id信息，就两三位老师没有。可能和我限制了Movie provider有关

**Comment by noir1216** [comment]
AVBASE,MGS,fc2,fc2hub,Caribbeancom,FANZA,JAV321,JavBus,ARZON,SOD,DUGA

**Comment by noir1216** [comment]
> > AVBASE,MGS,fc2,fc2hub,Caribbeancom,FANZA,JAV321,JavBus,ARZON,SOD,DUGA
> 
> provider里面不需要加上gfriends吗？🤔

gfriends是github上的一个女优头像库，只是帮你匹配对应女优名字的头像。provider才是确保你能削刮到女优名字信息。
我就是看没勾选provider之前，默认情况下很多都是FANZA削刮的，没有女优名字信息。才勾选的provider，手动排序

**Comment by noir1216** [comment]
provider里加上gfriends后，重新扫库一遍试试吧

**Comment by yarin1004** [comment]
这个问题 还没有解决。。
