### ISSUE TITLE
在Synology NAS上进行的Name Template更改未生效

### ISSUE THREAD

**Issue by onakahetta** [metatube-community/jellyfin-plugin-metatube#290]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.205.435

### MetaTube Server Version

1.2.2

### What OS are you seeing the problem on?
Synology OS

### Description

在Synology NAS上的Emby中，我尝试将Name Template更改为{number} {actors} {year}或{number} {year}，但结果只显示默认的{number} {title}。请帮助我。

### MetaTube Server
Koyeb

### Jellyfin/Emby Logs
Emby 4.8.1.0

### How to Reproduce

![IMG_7432](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/9284456/a2289ddc-7e90-4a68-ae16-e8c1691d245f)
![IMG_7433](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/9284456/7ffd7704-0287-408b-b88e-0a88287471fd)
K

**Comment by xjasonlyu** [comment]
你没有打开 enable template 吧
