### ISSUE TITLE
[Bug] 手动输入番号刮削后图片显示不全

### ISSUE THREAD

**Issue by dddd64693** [metatube-community/jellyfin-plugin-metatube#294]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2023.1215.2200.0

### MetaTube Server Version

最新版本

### Description

为什么很多图片都不能显示
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/14047878/f7338bc8-168f-4eca-9ec0-51f84db95601)

**Comment by dddd64693** [comment]
emby版本4.7.14.0

**Comment by QZQ-QSQ** [comment]
我也是，请大佬看看是什么原因。
