### ISSUE TITLE
[Bug] 最近用不了了，搜不到任何内容

### ISSUE THREAD

**Issue by Sostay** [metatube-community/jellyfin-plugin-metatube#314]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.205.435.0

### MetaTube Server Version

2024.205.435.0

### What OS are you seeing the problem on?

Windows

### Description

更换了美国和法国的都一样，什么都搜不到，但是koyeb的服务显示正常……

![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/6897274/7a01febf-c370-4b3a-a159-e52afad9c139)
![image](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/6897274/f0d05ad8-97e0-4bd9-9f9b-d5e3c7608e2b)

**Comment by yunpeng7** [comment]
我的koyeb上的几个docker都挂了

**Comment by NeroChen** [comment]
应该是墙导致无法访问到koyeb了

**Comment by Sostay** [comment]
> 应该是墙导致无法访问到koyeb了

试了下，好像是的，全局代理能搜到结果了。 
Jellyfin咋设置代理连接啊？我在联网里设置了下，好像不行。。

**Comment by yunpeng7** [comment]
Jellyfin设置代理没用，是插件的后端无法正常传输到你的NAS了
1、换个能正常传输的后端
2、本地部署后端，代理获取数据
我懒得折腾了，在等恢复

**Comment by Sostay** [comment]
> Jellyfin设置代理没用，是插件的后端无法正常传输到你的NAS了 1、换个能正常传输的后端 2、本地部署后端，代理获取数据 我懒得折腾了，在等恢复

我不是NAS，我是Windows上搞得

**Comment by CoOlaRlL** [comment]
换个没被墙的美国VPS部署吧

**Comment by Sostay** [comment]
更新：今天好像恢复了

**Comment by noir1216** [comment]
> 换个没被墙的美国VPS部署吧

vps用docker部署了，但是docker部署的怎么设置token呀？老哥

**Comment by 0BlackWhite0** [comment]
为啥我的koyeb都被封了

**Comment by noir1216** [comment]
> 为啥我的koyeb都被封了
koyeb 7天不登录就直接停机

**Comment by noir1216** [comment]
> 为啥我的koyeb都被封了

koyeb 7天不登录就直接停机

**Comment by yunpeng7** [comment]
后面NAS虚拟机装了openwrt做旁路由，一切正常了。

**Comment by yunpeng7** [comment]
我确认是IP被墙了，我办公室的NAS及电脑都无法正常访问后端服务器。办公室挂梯子又可以正常访问。
同样的，换个地点，换个网络环境也都可以。
于是通过NAS做旁路由把NAS放到墙外，一切正常了。

**Comment by Sostay** [comment]
> > 为啥我的koyeb都被封了
> 
> koyeb 7天不登录就直接停机

啊 不是一个月吗？

**Comment by CoOlaRlL** [comment]
> > 换个没被墙的美国VPS部署吧
> 
> vps用docker部署了，但是docker部署的怎么设置token呀？老哥

docker-compose.yaml配置文件里添加环境变量TOKEN
