### ISSUE TITLE
[Feature] 添加部分cos类影片的数据源

### ISSUE THREAD

**Issue by jsj1996m** [metatube-community/jellyfin-plugin-metatube#316]
### Description

部分cos影片(如cosh系列)目前无法在数据库中检索，

### Do you have a specific solution in mind?

https://konodare.wew.jp/<id>此网站提供相应的数据，包括演员姓名，标题，简介，发售日，影片时常等信息，是否考虑将本站加入数据库

**Comment by noir1216** [comment]
老哥推荐几部不错的cos类影片，之前下过几部，都是封面党，长得不好看
