### ISSUE TITLE
[Bug] 不能更换演员图片

### ISSUE THREAD

**Issue by 032** [metatube-community/jellyfin-plugin-metatube#319]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

最新版本

### MetaTube Server Version

最新版本

### What OS are you seeing the problem on?

macOS

### Description

不能更换演员图片,一直转圈圈在加载,,,电脑改成全局模式代理倒是可以,这是什么情况

**Comment by kk77mgj** [comment]
代理可以解决的都是网络问题

**Comment by noir1216** [comment]
> 代理可以解决的都是网络问题

根本不是代理的问题，就是我反馈的那个4.8不能写入演员MetaTube Id的问题，没有MetaTube Id，就不能手动选头像

**Comment by noir1216** [comment]
不想一个一个的手动添加演员的MetaTube Id，就重装emby4.7吧。反馈了问题起码半个月了，且不说能不能更新解决，仓库主根本不回复。

**Comment by xjasonlyu** [comment]
Fixed in #327 ; Also see #288
