### ISSUE TITLE
[Feature] 关于演员替换规则的一点建议

### ISSUE THREAD

**Issue by noir1216** [metatube-community/jellyfin-plugin-metatube#328]
### Description

例如 麻里梨夏 为我想要的被替换后的名字。
目前的规则是只能
```
涼野しずく=麻里梨夏
成海うるみ=麻里梨夏
広瀬りりあ=麻里梨夏
渚うるみ=麻里梨夏
早坂夏海=麻里梨夏
```
而不能直接
`涼野しずく=成海うるみ=広瀬りりあ=渚うるみ=早坂夏海=麻里梨夏`

还有就是查询这类女优名字的网站一般都是最新的名字在最前面。
如果metatube的规则是最新名字在最后的话，就没办法直接复制使用。

所以希望最终能做到的效果为：
`麻里梨夏=涼野しずく=成海うるみ=広瀬りりあ=渚うるみ=早坂夏海`

**Comment by simonlkch** [comment]
key  value的方法比較容易吧?
