### ISSUE TITLE
[Feature] 分享一個演員數據庫

### ISSUE THREAD

**Issue by Topbcy** [metatube-community/jellyfin-plugin-metatube#337]
### Description

希望能使插件完善，有演員的基本資料和照片
https://www.av-league.com

**Comment by Topbcy** [comment]
再補一個
https://avfan.mixh.jp/

**Comment by xjasonlyu** [comment]
感谢提供！

**Comment by xjasonlyu** [comment]
已更新：https://github.com/metatube-community/jellyfin-plugin-metatube/pull/338
