### ISSUE TITLE
[Bug] 更新新版本更换演员的刮削源以后，很多新放进去的演员出现了同名但是无法和之前重叠在一起的情况

### ISSUE THREAD

**Issue by ddddalex** [metatube-community/jellyfin-plugin-metatube#346]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2024.612.210.0

### MetaTube Server Version

v2024.612.210.0

### What OS are you seeing the problem on?

Other

### Description

更新新版本更换演员的刮削源以后，很多新放进去的演员出现了同名但是无法和之前演员同步在一起的情况，同名，照片都一样

**Comment by xjasonlyu** [comment]
是的，这是emby的机制，你需要刷新一下元数据，不用刷新图片

**Comment by ddddalex** [comment]
> 是的，这是emby的机制，你需要刷新一下元数据，不用刷新图片

是直接文件夹右键刷新元数据吗？

**Comment by xjasonlyu** [comment]
媒体库刷新元数据就行了

**Comment by ddddalex** [comment]
> 媒体库刷新元数据就行了

我把影片分了很多个媒体库，试了下单独刷新，还是和之前的对不上，需要把全部媒体库一个一个都刷新元数据吗
