### ISSUE TITLE
[Bug] javbus幾乎刮不到圖片

### ISSUE THREAD

**Issue by ITtest1** [metatube-community/jellyfin-plugin-metatube#348]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

最新

### MetaTube Server Version

最新

### What OS are you seeing the problem on?

Linux

### Description

javbus幾乎刮不到圖片，但是javbus的官網確實有圖片，我也嘗試使用我安裝metatube的vps的瀏覽器看javbus的官網也是有圖片。就是刮削的時候刮不到圖片

**Comment by xjasonlyu** [comment]
看來是更新了 Request Header 的要求，最新後端已經修復了。

**Comment by ITtest1** [comment]
> 看來是更新了Request Header的要求，最新的網關已經修復了。

我應該已經是最新了啊，也重啟了
![Screenshot_20240617_080906 (1)](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/87193498/d065b083-d2d1-466b-9127-89c170aadaba)
![Screenshot_20240617_080925 (1)](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/87193498/cf99be42-97d8-44e4-b2fe-f08793337671)

**Comment by xjasonlyu** [comment]
你要更新的是 MetaTube Server
