### ISSUE TITLE
[Bug] 同一个演员会重复生成

### ISSUE THREAD

**Issue by localgr** [metatube-community/jellyfin-plugin-metatube#350]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

612.210

### MetaTube Server Version

MetaTube 1.2.6

### What OS are you seeing the problem on?

Linux

### Description

emby版本：4.8.6

影片重新刮削一下就会在数据库里创建一个演员（同名，同图片）刮削一次就会重新创建一个。
![屏幕截图_17-6-2024_22055_192 168 31 1](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/66309186/faf8de06-1b8f-45ad-bea4-79bafd06ea7c)
在几天前是没问题的，感觉是最近更新的这个版本的问题。

### MetaTube Server Logs

无

**Comment by xjasonlyu** [comment]
你有试过刷新元数据吗，emby默认是会这样的

**Comment by okeidoki** [comment]
同样问题。Gfriends,Xslist,AV-league

**Comment by ddddalex** [comment]
是有点痛苦，刷新了有时候有用有时候没用，估计还是调整了人物刮削源的问题

**Comment by yarin1004** [comment]
> 你有试过刷新元数据吗，emby默认是会这样的

越刷新越多

**Comment by AbcdefgXW** [comment]
同问，我也是，而且越刷越多

**Comment by cyanbees** [comment]
同样的问题，不清楚是什么原因导致，
