### ISSUE TITLE
[Bug] 无法刮削caribbean的影片

### ISSUE THREAD

**Issue by Watercolor-tone** [metatube-community/jellyfin-plugin-metatube#351]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2024.612.210.0

### MetaTube Server Version

metatube/metatube-server:1.2.6

### Description

使用Emby，无法刮削caribbean的影片：
https://www.caribbeancom.com/moviepages/062715-909/index.html
只搜标题和女优的话，并没有caribbean这个网站的数据。
emby刮削元数据【MetaTube Id：】里面输入Caribbeancom:062715-909，则是转30秒就显示未找到符合您搜索条件的项目。
我并不确定【MetaTube Id：】这个框内应该填什么，“Caribbeancom:062715-909”是我对比了一下其他正常刮削的信息编出来的。
其他影片是正常刮削的，唯独这个caribbean的无法刮削。

### emby刮削元数据，搜索女优名字

`{"level":"info","ts":1718810491.4520564,"caller":"engine/movie.go:137","msg":"Search keyword 愛沢かりん: AIRAV(28.27µs): invalid keyword Caribbeancom(60.051µs): invalid id PACOPACOMAMA(54.43µs): invalid id XXX-AV(112.01µs): invalid id Getchu(153.577µs): invalid id H0930(188.281µs): invalid id Gcolle(669.691µs): invalid id FC2(695.255µs): invalid id 1Pondo(731.339µs): invalid id CaribbeancomPR(763.104µs): invalid id HeyDouga(811.605µs): invalid id 10musume(1.322659ms): invalid id MURAMURA(1.360577ms): invalid id HEYZO(1.397287ms): invalid id MYWIFE(1.491378ms): invalid id C0930(1.523978ms): invalid id KIN8(1.556675ms): invalid id TOKYO-HOT(1.609424ms): invalid keyword Pcolle(1.667529ms): invalid id H4610(1.748254ms): invalid id fc2hub(1.75898ms): invalid keyword AVBASE(1.771723ms): Get \"https://www.avbase.net/\": dial tcp 151.101.90.132:443: i/o timeout DAHLIA(924.625768ms): <nil> MGS(1.144021109s): Forbidden FANZA(1.294699909s): not-available-in-your-region SOD(3.359046659s): <nil> ARZON(3.922410573s): <nil> AVE(5.813813558s): <nil> JAV321(10.002787957s): Post \"https://www.jav321.com/search\": context deadline exceeded (Client.Timeout exceeded while awaiting headers) DUGA(30.017127918s): Get \"https://duga.jp/search/=/q=%E6%84%9B%E6%B2%A2%E3%81%8B%E3%82%8A%E3%82%93/\": dial tcp 162.125.32.6:443: i/o timeout FALENO(30.017130788s): Get \"https://faleno.jp/top/?s=%E6%84%9B%E6%B2%A2%E3%81%8B%E3%82%8A%E3%82%93\": dial tcp 184.72.1.148:443: i/o timeout JavBus(30.017141914s): <nil>"}`

**Comment by xjasonlyu** [comment]
可以搜到和刮削，没问题。

**Comment by Watercolor-tone** [comment]
> 可以搜到和刮削，没问题。

请问一下，我该怎么刮削这个影片呢？在【MetaTube ID：】里，我应该填什么信息，因为我搜片名是搜不出来的。

**Comment by 86-hachiroku** [comment]
> 请问一下，我该怎么刮削这个影片呢？在【MetaTube ID：】里，我应该填什么信息，因为我搜片名是搜不出来的。

Name填入或影片目录命名为编号即可，请注意caribbean编号使用中划线而caribbeanpr使用下划线，即
caribbean: `^\d{6}_\d{3}$`
caribbeanpr: `^\d{6}_\d{3}$`

你可以在每个provider的NormalizeMovieID函数中找到对应的命名规则
https://github.com/metatube-community/metatube-sdk-go/tree/main/provider
https://github.com/metatube-community/metatube-sdk-go/blob/main/provider/caribbeancom/caribbeancom.go#L42
