### ISSUE TITLE
[错误]存储库URL为什么只能下载到2024.205.435.0

### ISSUE THREAD

**Issue by benxiaohai15** [metatube-community/jellyfin-plugin-metatube#357]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.205.435.0

### MetaTube Server Version

metatube/metatube-server:1.2.6

### What OS are you seeing the problem on?

Other

### Description

![截屏2024-06-28 18 53 48](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/85447593/db2a39a2-cd1c-4ce3-9ca5-682dd15bcdee)

![Uploading 截屏2024-06-28 18.53.48.png…]()

**Comment by benxiaohai15** [comment]
![Uploading 截屏2024-06-28 18.53.48.png…]()

**Comment by kk77mgj** [comment]
更新jellyfin版本到10.9
