### ISSUE TITLE
[Feature] arzon刮削结果的番号不标准，前面比起正常的番号多了个1位数字，能去除吗？

### ISSUE THREAD

**Issue by Jade9nan** [metatube-community/jellyfin-plugin-metatube#367]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

latest (docker)

### What OS are you seeing the problem on?

Linux

### Description

Truenas Scale 24

没有日志，有截图
而且应该也不是MetaTube的问题

设置截图
![图片](https://github.com/user-attachments/assets/9054a9f2-3cfa-4bc0-bc6f-71532accf166)

媒体截图
![图片](https://github.com/user-attachments/assets/b5871403-5be6-4902-aeae-0c47042ec9c7)
![图片](https://github.com/user-attachments/assets/01de4be5-2bef-44c1-b8c7-4e7eb644e2aa)
![图片](https://github.com/user-attachments/assets/3f82b4e9-6a39-4331-8c51-e1619c63f307)

**Comment by xjasonlyu** [comment]
这是Arzon默认的番号名，它似乎有多个同样的影片但是是不同的番号。
