### ISSUE TITLE
@Animism001 填入http://localhost:xxxx/即可，xxxx是你的port。

### ISSUE THREAD

**Issue by poko11** [metatube-community/jellyfin-plugin-metatube#373]
@Animism001 填入http://localhost:xxxx/即可，xxxx是你的port。

_Originally posted by @adamlin30 in https://github.com/metatube-community/jellyfin-plugin-metatube/discussions/29#discussioncomment-4617792_

我在地址栏输入本机IP:7070连不上，用你说的http://localhost:7070也不行，但是3fe7a6fda493   metatube/metatube-server:latest   "/metatube-server -d…"   28 minutes ago   Up 28 minutes   0.0.0.0:7070->7070/tcp   metatube 又能检测出来

**Comment by xjasonlyu** [comment]
关了，大概是发错了。
