### ISSUE TITLE
[Bug] 帮助页部分链接失效

### ISSUE THREAD

**Issue by thelastfantasy** [metatube-community/jellyfin-plugin-metatube#378]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

latest

### MetaTube Server Version

latest

### Description

https://metatube-community.github.io/wiki/provider-filter/
链接404，比如这里的**数据来源**超链接

**Comment by xjasonlyu** [comment]
感谢，已修复。
