### ISSUE TITLE
[Bug] 有的片内含多个视频的话，Jellyfin刮削后只能在Web UI媒体库内显示1个视频

### ISSUE THREAD

**Issue by Jade9nan** [metatube-community/jellyfin-plugin-metatube#380]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

latest

### MetaTube Server Version

latest

### Description

![图片](https://github.com/user-attachments/assets/9c0dc56a-4084-451a-88e6-433972b3d616)

![图片](https://github.com/user-attachments/assets/ccb841c5-790e-4a67-8a40-c501ea1f48c2)

如图，也就是应该按照文件夹处理的时候，缺只处理了文件夹里发现的第一个视频，类似这样的情况应该如何解决？
问题出现的原因我猜测可能是刮削获得的剧集数只有1个？
媒体库是影片模式，非TV或混合模式

下面这个目录结构相似度很高，但是里面的4个文件就都能识别（虽然4个文件识别出来的标题一样，刮削后需要手动修改标题）
![图片](https://github.com/user-attachments/assets/43918860-a752-4f40-9948-5b247cf797b1)
![图片](https://github.com/user-attachments/assets/d3cb08d2-2699-4ceb-8e6c-3ef8f954791d)

**Comment by Jade9nan** [comment]
补充：
![图片](https://github.com/user-attachments/assets/e7d11a67-0acd-439e-849a-68cd596d8fa7)

好像是把3个文件识别成一部片的3个版本了，正确的话应该是识别成3个片段A, B, C才对

**Comment by xjasonlyu** [comment]
命名不对，参考这个：<https://metatube-community.github.io/wiki/naming-rules/#_6>

**Comment by Jade9nan** [comment]
> 命名不对，参考这个：https://metatube-community.github.io/wiki/naming-rules/#_6

![图片](https://github.com/user-attachments/assets/c577e840-bf5a-42ab-984b-f9e7bec03957)
![图片](https://github.com/user-attachments/assets/b0e4444d-f58d-4cdd-96bd-c47d180b66f4)

命名修改了，但还是一样的问题

**Comment by xjasonlyu** [comment]
`-cdX`必须是后缀，你后面带中括号了 Emby 就是识别不出来了。

**Comment by Jade9nan** [comment]
> `-cdX`必须是后缀，你后面带中括号了 Emby 就是识别不出来了。

谢谢！识别出来了！
不过这样感觉有点不方便，我习惯把下载的视频转换成AV1以减小体积，但使用的handbrake没有覆盖原文件或删除原文件功能，所以转换后一般需要加个[AV1 Opus]这样的标签，这样的标签后面再加你说的-cdx后缀的话就感觉看着挺别扭的，文件重命名的时候也挺复杂。
所以如果可能的话希望metatube能把文件名中多余的格式标签如`[av1-10bit opus]`过滤掉再trim之后再查找-cdx或-C这样的标记，不知是否可行？

**Comment by xjasonlyu** [comment]
> 所以如果可能的话希望metatube能把文件名中多余的格式标签如[av1-10bit opus]过滤掉再trim之后再查找-cdx或-C这样的标记，不知是否可行？

这是由 Emby/Jellyfin 决定的，插件是没法做到的。

**Comment by Jade9nan** [comment]
> > 所以如果可能的话希望metatube能把文件名中多余的格式标签如[av1-10bit opus]过滤掉再trim之后再查找-cdx或-C这样的标记，不知是否可行？
> 
> 这是由 Emby/Jellyfin 决定的，插件是没法做到的。

原来如此，谢谢！
