### ISSUE TITLE
[Bug] 我在emby安装了metatube，后台上传带宽疯狂跑

### ISSUE THREAD

**Issue by kylinbaozi** [metatube-community/jellyfin-plugin-metatube#383]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

last

### MetaTube Server Version

last

### What OS are you seeing the problem on?

Windows

### Description

emby一直处于6m上传速度上，重启服务器没用，禁用插件后重启就正常了...

**Comment by xjasonlyu** [comment]
不清楚你的环境是啥样的，但一般和插件没有直接关系，我猜可能是你的资源有什么问题然后一直触发刷新之类的？但是理论上也不会造成这种上传。感觉你需要排查一下本地的问题先，这种高上传更像是BT之类的造成的。
