### ISSUE TITLE
[Feature] 可否开放影片的预览图刮削功能？

### ISSUE THREAD

**Issue by brighteast1988** [metatube-community/jellyfin-plugin-metatube#389]
### Description

AVDC和MVDC等优秀的同行刮削器都具备影片预览图的刮削与下载保存功能，请问咱们能不能也开放这个功能。

### Do you have a specific solution in mind?

我知道会有一些目录结构的issue，但这不妨碍功能的开放，只需要在这个功能开关上增加一个小说名，建议影片处于单独文件夹下，即可解决。

那种很多影片文件扔在同一个目录下的，程序可以默认不给他下载extrascene（预览图）

**Comment by xjasonlyu** [comment]
MetaTube插件和AVDC/MVDC不同，MetaTube本身不会保存任何文件到你的目录，所有行为都是Emby/Jellyfin定义的，所以Emby/Jellyfin如果不支持影片预览图的刮削与下载保存功能，那本插件也无法实现这个功能。
