### ISSUE TITLE
[Bug] FC2的影片元数据无法刮削

### ISSUE THREAD

**Issue by tcwth556** [metatube-community/jellyfin-plugin-metatube#391]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

latest

### What OS are you seeing the problem on?

群晖7.2

### Description

不知道是不是之前的fc2hub.com域名换成javten.com导致出的问题。
![1](https://github.com/user-attachments/assets/3865a71e-ad3b-4b39-a0aa-aa56bd24947e)
![2](https://github.com/user-attachments/assets/ae53a052-3aa5-4838-867e-45b0cdfa1992)
刮削之前刮削过的影片也是找不到fc2hub的元数据有别的元数据，不是我这里网络的问题。图二是搜索FC2-4530010，之前是刮削的到的。

### MetaTube Server Logs

<html>
<body>

2024/09/10 16:41:31 | stdout | [0.355ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "4530010" COLLATE NOCASE OR id = "4530010" COLLATE NOCASE
-- | -- | --
2024/09/10 16:41:31 | stdout | [GORM] 2024/09/10 08:41:31 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
2024/09/10 16:41:31 | stdout | {"level":"info","ts":1725957691.7848454,"caller":"engine/movie.go:137","msg":"Search keyword 4530010: HeyDouga(1.415245ms): invalid id CaribbeancomPR(1.655548ms): invalid id AIRAV(1.919431ms): invalid keyword 10musume(8.557645ms): invalid id MURAMURA(9.450364ms): invalid id Pcolle(10.061361ms): invalid id 1Pondo(11.210324ms): invalid id PACOPACOMAMA(12.080453ms): invalid id Caribbeancom(16.451582ms): invalid id AVBASE(1.422731084s): <nil> JAV321(1.496785352s): <nil> fc2hub(1.880715792s): <nil> HEYZO(1.894566095s): Not Found MGS(1.931010428s): Forbidden JavBus(2.111904975s): <nil> H0930(2.143243592s): incomplete metadata SOD(2.173784709s): Forbidden KIN8(2.252469198s): Not Found Gcolle(2.600674504s): Not Found H4610(2.65650503s): incomplete metadata C0930(2.709398625s): incomplete metadata MYWIFE(3.116481141s): Internal Server Error AVE(3.204959448s): <nil> Getchu(3.278999836s): Not Found FANZA(3.407324493s): not-available-in-your-region DAHLIA(3.523542217s): <nil> DUGA(3.790405114s): <nil> TOKYO-HOT(3.911258279s): <nil> FC2(4.26354419s): incomplete metadata FALENO(4.374614187s): <nil> XXX-AV(4.495875816s): incomplete metadata ARZON(5.216834928s): <nil>"}
2024/09/10 16:41:26 | stdout | [0.388ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "XXX-AV" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [1.874ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "MYWIFE" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [0.307ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "Gcolle" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [0.311ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "C0930" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [13.266ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "HEYZO" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [11.357ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "FC2" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [0.599ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "H0930" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [2.386ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "Getchu" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [0.385ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "KIN8" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:41:26 | stdout | [0.371ms] [rows:0] SELECT * FROM `movie_metadata` WHERE provider = "H4610" AND id = "4530010" COLLATE NOCASE ORDER BY `movie_metadata`.`id` LIMIT 1
2024/09/10 16:41:26 | stdout | [GORM] 2024/09/10 08:41:26 github.com/metatube-community/metatube-sdk-go/engine/movie.go:197 record not found
2024/09/10 16:39:51 | stdout | [GIN] 2024/09/10 - 08:39:50 \| 200 \|  3.037244695s \|     192.168.1.7 \| GET      "/v1/images/primary/DUGA/sekimen-0233?url=https%3a%2f%2fpic.duga.jp%2funsecure%2fsekimen%2f0233%2fnoauth%2fjacket_240.jpg&ratio=-1&pos=1&auto=True&quality=100"
2024/09/10 16:39:50 | stdout | [GIN] 2024/09/10 - 08:39:50 \| 200 \|  2.899872589s \|     192.168.1.7 \| GET      "/v1/images/primary/DUGA/sekimen-0163?url=https%3a%2f%2fpic.duga.jp%2funsecure%2fsekimen%2f0163%2fnoauth%2fjacket_240.jpg&ratio=-1&pos=1&auto=True&quality=100"
2024/09/10 16:39:50 | stdout | [GIN] 2024/09/10 - 08:39:50 \| 200 \|  2.611743436s \|     192.168.1.7 \| GET      "/v1/images/primary/DUGA/sekimen-0191?url=https%3a%2f%2fpic.duga.jp%2funsecure%2fsekimen%2f0191%2fnoauth%2fjacket_240.jpg&ratio=-1&pos=1&auto=True&quality=100"
2024/09/10 16:39:47 | stdout | [GIN] 2024/09/10 - 08:39:47 \| 200 \|    5.4070533s \|     192.168.1.5 \| GET      "/v1/movies/search?q=4528048&provider=&fallback=True"
2024/09/10 16:39:47 | stdout | [0.566ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "4528048" COLLATE NOCASE OR id = "4528048" COLLATE NOCASE

</body>
</html>

**Comment by holll** [comment]
就是因为换域名出现的问题，我开PR了，可以先用我的[版本](https://github.com/holll/metatube-sdk-go/releases/tag/v1.2.6-fix)

**Comment by loveFc2** [comment]
> 就是因为换域名出现的问题，我开PR了，可以先用我的[版本](https://github.com/holll/metatube-sdk-go/releases/tag/v1.2.6-fix)

请问怎么用

**Comment by xjasonlyu** [comment]
Fixed in https://github.com/metatube-community/metatube-sdk-go/pull/96
