### ISSUE TITLE
[Feature] 搜出来的封面和实际显示的不一样

### ISSUE THREAD

**Issue by karasfjm** [metatube-community/jellyfin-plugin-metatube#396]
### Description

如题，哪怕我自己找的图片上传都不行，有没有解决办法？

**Comment by xjasonlyu** [comment]
因为有些源的预览图和实际的海报就是不一样的。自己上传不行的话可能就是emby/jellyfin的问题了？

**Comment by karasfjm** [comment]
> 因为有些源的预览图和实际的海报就是不一样的。自己上传不行的话可能就是emby/jellyfin的问题了？

我试过EMBY和JELLYFIN的不同版本，都是这个样子，搞不懂了
