### ISSUE TITLE
[Bug] 反复测试下来v1.2.5能搜到的元数据最全，1.2.6和1.2.7同样的片源搜刮到的元数据都会少一半，什么原因？

### ISSUE THREAD

**Issue by stjacob** [metatube-community/jellyfin-plugin-metatube#397]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

newest

### MetaTube Server Version

1.2.5 1.2.7

### What OS are you seeing the problem on?

Linux

### Description

反复测试下来v1.2.5能搜到的元数据最全，1.2.6和1.2.7同样的片源搜刮到的元数据都会少一半，什么原因？

**Comment by xjasonlyu** [comment]
能提供一下少了哪些数据吗？
