### ISSUE TITLE
[Bug] FC2刮削失败

### ISSUE THREAD

**Issue by zshakelove** [metatube-community/jellyfin-plugin-metatube#400]
### Verify steps

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

Docker deploy metatube-server:latest

### What OS are you seeing the problem on?

Windows

### Description

后端是docker部署在koyeb上的。其他的影片可以正常刮削，FC2的不行，截图为服务端情况
![Snipaste_2024-09-29_20-08-12](https://github.com/user-attachments/assets/7cf3bb39-c919-4ef0-b726-a315b98c3bce)

### MetaTube Server Logs

[GIN] 2024/09/29 - 11:58:17 | 404 |  858.363238ms |   203.198.34.21 | GET      "/v1/images/primary/fc2hub/896085-1921054?url=https%3a%2f%2fstorage26000.contents.fc2.com%2ffile%2f342%2f34110922%2f1626204717.83.png&ratio=-1&pos=1&auto=True&quality=90"
[GIN] 2024/09/29 - 11:58:34 | 404 |  868.630056ms |   203.198.34.21 | GET      "/v1/images/backdrop/fc2hub/896085-1921054?ratio=-1&pos=-1&auto=False&quality=90"

**Comment by Topbcy** [comment]
沒用，FC2有反爬蟲

**Comment by lamesbond** [comment]
坏了，我也碰到了，梯子换别的地区节点能刮一部分。
等几天看能不能解除风控

**Comment by liya1413** [comment]
我发现了一个问题用云服务器VPS削挂FC2的会出现图片无法正常打开的情况，番号的都正常 就FC2有这个问题，换成本地挂梯子削挂的图片正常访问，试了好几个国家的VPS都这样
