### ISSUE TITLE
[Feature] 后端自己搭建的教程看的不是很明白

### ISSUE THREAD

**Issue by zlyMaster** [metatube-community/jellyfin-plugin-metatube#406]
### Description

我的操作步骤如下：
1.阿里云服务器（denterOS7.9 香港IP）下载了linux版本的metatube，解压并执行；
2.打开jellyfin控制台->我的插件->metatube，编辑，找到server配置项填写为"https://XX.XX.XXX.XXX:8080/"(XX.XX.XXX.XXX是阿里云服务器的公有IP，这一步不知道是否有问题)。

刮削没有成功，不知道是操作步骤有问题，还是有其他需要的步骤没有做。
建议可以把端到端的详细教程补齐一份，网上使用人数不多，也找不到什么资料。

**Comment by zlyMaster** [comment]
./metatube-server -dsn metatube.db

**Comment by zlyMaster** [comment]
补充一下运行命令：./metatube-server -dsn config/metatube.db

**Comment by xjasonlyu** [comment]
如果没有公网ip的话，插件没发连接上那是肯定没法用的吧？

**Comment by zlyMaster** [comment]
阿里云有公网ip和私有ip，我使用的公网ip，ping可以ping通，运行metatube的时候默认是debug模式，我这样设置之后，手动出发刮削没有日志打印，是不是访问没有成功，步骤是不是对的

**Comment by zlyMaster** [comment]
> 阿里云有公网ip和私有ip，我使用的公网ip，ping可以ping通，运行metatube的时候默认是debug模式，我这样设置之后，手动出发刮削没有日志打印，是不是访问没有成功，步骤是不是对的

**Comment by zlyMaster** [comment]
> 如果没有公网ip的话，插件没发连接上那是肯定没法用的吧？

阿里云有公网ip和私有ip，我使用的公网ip，ping可以ping通，运行metatube的时候默认是debug模式，我这样设置之后，手动出发刮削没有日志打印，是不是访问没有成功，步骤是不是对的

**Comment by xjasonlyu** [comment]
会不会是你没配置ssl但是却用的https来访问的原因？

**Comment by zlyMaster** [comment]
> 如果没有公网ip的话，插件没发连接上那是肯定没法用的吧？

[root@iZj6c7aw1i8i0z96avfl1xZ metatube]# ./metatube-server -dsn config/metatube.db -port 4819
lib/jpegli/decode_marker.cc:504: Did not find SOI marker.
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:32
[0.365ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_metadata"
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:117
[0.109ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "movie_metadata" AND sql IS NOT NULL order by type = "table" desc
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:125
[0.085ms] [rows:-] SELECT * FROM `movie_metadata` LIMIT 1
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:32
[0.030ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="actor_metadata"
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:117
[0.069ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "actor_metadata" AND sql IS NOT NULL order by type = "table" desc
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:125
[0.060ms] [rows:-] SELECT * FROM `actor_metadata` LIMIT 1
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:32
[0.023ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="movie_reviews"
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:117
[0.059ms] [rows:1] SELECT sql FROM sqlite_master WHERE type IN ("table","index") AND tbl_name = "movie_reviews" AND sql IS NOT NULL order by type = "table" desc
[GORM] 2024/10/07 23:13:23 github.com/glebarez/sqlite@v1.11.0/migrator.go:125
[0.031ms] [rows:-] SELECT * FROM `movie_reviews` LIMIT 1
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> github.com/metatube-community/metatube-sdk-go/route.New.getIndex.func4 (4 handlers)
[GIN-debug] GET    /v1/modules               --> github.com/metatube-community/metatube-sdk-go/route.New.getModules.func5 (5 handlers)
[GIN-debug] GET    /v1/providers             --> github.com/metatube-community/metatube-sdk-go/route.getProviders.func1 (5 handlers)
[GIN-debug] GET    /v1/translate             --> github.com/metatube-community/metatube-sdk-go/route.New.getTranslate.func6 (5 handlers)
[GIN-debug] GET    /v1/images/primary/:provider/:id --> github.com/metatube-community/metatube-sdk-go/route.New.getImage.func7 (5 handlers)
[GIN-debug] GET    /v1/images/thumb/:provider/:id --> github.com/metatube-community/metatube-sdk-go/route.New.getImage.func8 (5 handlers)
[GIN-debug] GET    /v1/images/backdrop/:provider/:id --> github.com/metatube-community/metatube-sdk-go/route.New.getImage.func9 (5 handlers)
[GIN-debug] GET    /v1/db/version            --> github.com/metatube-community/metatube-sdk-go/route.New.getDBVersion.func11 (5 handlers)
[GIN-debug] GET    /v1/actors/:provider/:id  --> github.com/metatube-community/metatube-sdk-go/route.New.getInfo.func12 (5 handlers)
[GIN-debug] GET    /v1/actors/search         --> github.com/metatube-community/metatube-sdk-go/route.New.getSearch.func13 (5 handlers)
[GIN-debug] GET    /v1/movies/:provider/:id  --> github.com/metatube-community/metatube-sdk-go/route.New.getInfo.func14 (5 handlers)
[GIN-debug] GET    /v1/movies/search         --> github.com/metatube-community/metatube-sdk-go/route.New.getSearch.func15 (5 handlers)
[GIN-debug] GET    /v1/reviews/:provider/:id --> github.com/metatube-community/metatube-sdk-go/route.New.getReview.func16 (5 handlers)

这是服务器上运行的日志没有其他打印了，jellyfin配置了metatube插件，触发过手动刮削

**Comment by zlyMaster** [comment]
> 会不会是你没配置ssl但是却用的https来访问的原因？

我是用http再试试

**Comment by zlyMaster** [comment]
> 会不会是你没配置ssl但是却用的https来访问的原因？

我刚试过了http也没有打印

**Comment by zlyMaster** [comment]
或者可不可以私信我一个已有的后端ip和端口号，我试试看看是不是配置错误

**Comment by zlyMaster** [comment]
是配置问题，我用改成本地可以刮削
