### ISSUE TITLE
[Feature] centerOS7.9 上启动metatube只监听了ipv6端口，有办法通过监听ipv4端口启动吗，我的服务器没有ipv6的公网ip/域名

### ISSUE THREAD

**Issue by zlyMaster** [metatube-community/jellyfin-plugin-metatube#407]
### Description

有办法通过参数设置监听ipv4端口启动吗

### Is this feature related to a specific bug?

>netstat -tuln

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::4819                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN     

4819端口为我设置的metatube端口，只有tcp6启动了监听

**Comment by xjasonlyu** [comment]
-host 0.0.0.0 -port 8080 这样子不行吗？

**Comment by zlyMaster** [comment]
> -host 0.0.0.0 -port 8080 这样子不行吗？

lib/jpegli/decode_marker.cc:504: Did not find SOI marker.
flag provided but not defined: -host
Usage:
  -bind string
        Bind address of server
  -db-auto-migrate
        Database auto migration
  -db-max-idle-conns int
        Database max idle connections
  -db-max-open-conns int
        Database max open connections
  -db-prepared-stmt
        Database prepared statement
  -dsn string
        Database Service Name
  -port string
        Port number of server (default "8080")
  -request-timeout duration
        Timeout per request (default 1m0s)
  -token string
        Token to access server
  -version
        Show version

指定不了host，识别不了host参数

**Comment by xjasonlyu** [comment]
写错了，-bind不是-host。另外你这是linux amd64么？

**Comment by zlyMaster** [comment]
> 写错了，-bind不是-host。另外你这是linux amd64么？

我试试哈，对amd64 centerOS 7.9

**Comment by zlyMaster** [comment]
> 写错了，-bind不是-host。另外你这是linux amd64么？

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::4819                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN 

还是使用的ipv6的端口监听的，ipv4没有，其他端口都是ipv4和ipv6都有的

**Comment by Alex92748** [comment]
感觉可以用nginx解决，nginx监听ipv6，再反代到本地的8080
