### ISSUE TITLE
[Bug] 封面截取逻辑待优化

### ISSUE THREAD

**Issue by Bennie-CHEN** [metatube-community/jellyfin-plugin-metatube#409]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

1.2.7

### What OS are you seeing the problem on?

Linux

### Description

封面展示的截取待优化，未截取到该图的左侧作为主要图像
https://image.mgstage.com/images/jackson/sp/390jnt/073/pake-03_sp-390jnt-073.jpg

### MetaTube Server

，

### Jellyfin/Emby Logs

，

### MetaTube Server Logs

，

### How to Reproduce

，

**Comment by xjasonlyu** [comment]
我这边没有什么问题好像，这个番号就是人脸识别后截取的左侧部分。

**Comment by Bennie-CHEN** [comment]
> 我这边没有什么问题好像，这个番号就是人脸识别后截取的左侧部分。

对于人脸识别截取的功能，在插件设置处，以及美体裤设置，需要做什么设置吗？我的封面截取出来是这样的（红色方块是我打的马赛克）
![IMG_7867](https://github.com/user-attachments/assets/10a90252-4d83-406c-81d2-1e888f62b9a1)

**Comment by xjasonlyu** [comment]
能不能提供一下你后端部署系统的配置信息，比如cpu，内存，操作系统具体版本等信息？

**Comment by Bennie-CHEN** [comment]
> 能不能提供一下你后端部署系统的配置信息，比如cpu，内存，操作系统具体版本等信息？

CPU：Intel® Processor N95

内存：三星 LPDDR5 板载单颗粒 8GB

硬盘：1 x M.2 2242 NVMe/SATA(NGFF) 自适应，NVMe为PCIe 3.0 x 2速率

固件：istoreos-22.03.7-2024080210-x86-64-squashfs-combined-efi

**Comment by xjasonlyu** [comment]
操作系统呢，然后具体用的是哪个后端二进制文件？

**Comment by Bennie-CHEN** [comment]
> istoreos-22.03.7

操作系统就是：istoreos-22.03.7

后端用的docker pull的latest，目前是1.2.7

**Comment by Bennie-CHEN** [comment]
> 操作系统呢，然后具体用的是哪个后端二进制文件？

操作系统就是：istoreos-22.03.7

后端用的docker pull的latest，目前是1.2.7

**Comment by Bennie-CHEN** [comment]
> 操作系统呢，然后具体用的是哪个后端二进制文件？

大佬有啥建议吗？

**Comment by xjasonlyu** [comment]
很奇怪，我没法复现，因为我这边是好的没啥问题 👀

**Comment by Bennie-CHEN** [comment]
> 很奇怪，我没法复现，因为我这边是好的没啥问题 👀

那……先不管吧，强迫症难受
