### ISSUE TITLE
不带番号的视频能不能不刮削了

### ISSUE THREAD

**Issue by lamesbond** [metatube-community/jellyfin-plugin-metatube#411]
### Description

我的媒体库里有av，fc2这些可以正常刮削的，也有国产的，自拍的，only fans等，这些不应该刮削的也会匹配到一个番号

### Do you have a specific solution in mind?

建议用文件名过滤一下，文件名中不带“abcd-123”格式的番号直接不刮削了，这样文件名就是标题，封面会用image capture抓取

**Comment by xjasonlyu** [comment]
不同人文件命名风格不同，很难根据文件名明明就判断出是否有需要。还是建议按媒体库分类。就像你不会把电视剧和电影放在同一个媒体库里一样的。

**Comment by lamesbond** [comment]
wiki写了命名规范，就按写的规则过滤文件名呗

**Comment by Topbcy** [comment]
建議你還是按媒體庫分類
