### ISSUE TITLE
[Feature] 建议增加jav的预告片和预览图和简介的刮削，另外反馈一个bug

### ISSUE THREAD

**Issue by zlyMaster** [metatube-community/jellyfin-plugin-metatube#413]
### Description

建议可以增加**预告片**和**预览**图和**简介**的刮削，片太多的，只有封面的话，选片观赏的时候会很麻烦，av片商的公司网站上有预告片和简介还有预览图，加上了之后在选片观赏的时候会比较方便。

另外就是使用的时候发现一个bug：jellyfin媒体库设置里，设置最大背景图数量大于1的时候会有大量的影片刮削不到，但是设置为1重新扫描刮削就好了。

**Comment by xjasonlyu** [comment]
> 建议可以增加预告片和预览图和简介的刮削，片太多的，只有封面的话，选片观赏的时候会很麻烦，av片商的公司网站上有预告片和简介还有预览图，加上了之后在选片观赏的时候会比较方便。

这不是一直都有的吗（

> 另外就是使用的时候发现一个bug：jellyfin媒体库设置里，设置最大背景图数量大于1的时候会有大量的影片刮削不到，但是设置为1重新扫描刮削就好了。

不清楚这是不是什么Jellyfin的奇怪设置，emby下没这个问题倒是。。

**Comment by zlyMaster** [comment]
预告片没按操作来

**Comment by looper13** [comment]
> 预告片没按操作来

预览图 能实现不
