### ISSUE TITLE
[Bug] ARZON数据源问题

### ISSUE THREAD

**Issue by Bennie-CHEN** [metatube-community/jellyfin-plugin-metatube#414]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

1.2.7

### What OS are you seeing the problem on?

Linux

### Description

对于 ARZON:1667598（车牌：MIMK-103）
这种，ARZON数据源里面演员元数据丢失的问题，如何规避及解决？
至少FANZA是能正常关联出演员的

**Comment by xjasonlyu** [comment]
因为Arzon这个番号就是没有演员的。

**Comment by Bennie-CHEN** [comment]
> 因为Arzon这个番号就是没有演员的。

是的我明白，所以在探究是不是应该按优先级从多个数据源，取非空值，以避免Arzon元数据不全的情况

**Comment by xjasonlyu** [comment]
这样就涉及到了多个数据源聚合的问题，你很难保证两个数据源是一个影片的，同番号的影片是很多的。

**Comment by Bennie-CHEN** [comment]
好吧，我还以为整个日本产业从产业程度对于车牌号的管理做了唯一
不过我还是很好奇，真的有同番号得吗，可不可以给我个例子
另外有一个日本人做的百科全书资料库：https://av-help.memo.wiki/
大佬可以看看

**Comment by Bennie-CHEN** [comment]
> 这样就涉及到了多个数据源聚合的问题，你很难保证两个数据源是一个影片的，同番号的影片是很多的。

好吧，我还以为整个日本产业从产业层面对于车牌号的管理做了唯一
不过我还是很好奇，真的有同番号得吗，可不可以给我个例子
另外有一个日本人做的百科全书资料库：https://av-help.memo.wiki/
大佬可以看看

**Comment by xjasonlyu** [comment]
比如MIDV这个车牌就有很多的旧号。
