### ISSUE TITLE
[Bug] providers没编译全嘛？

### ISSUE THREAD

**Issue by Not-a-good-username** [metatube-community/jellyfin-plugin-metatube#416]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

2024.612.210.0

### MetaTube Server Version

v1.2.7-43f17e0

### What OS are you seeing the problem on?

Linux

### Description

docker部署metatube，起初是因为没有办法刮削国产，然后访问ip+端口号/v1/provider，发现并没有madouqu的provider，想着是不是配置文件问题，于是添加了MT_MOVIE_PROVIDER_PRIORITY_MadouQu=1000，但依旧无法看到madouqu的provider，想着是不是没有把madouqu的provider编译进去？又或者出于什么原因默认不启用，需要自行编译？
（在metatube server中贴出了我的ip+端口号/v1/provide的完整输出，其中并没有madouqu，已确保docker镜像最新并添加正确的配置文件，按官网教程，仅修改端口号）

### MetaTube Server

{
    "data": {
        "actor_providers": {
            "AV-LEAGUE": "https://www.av-league.com/",
            "Gfriends": "https://github.com/gfriends/gfriends"
        },
        "movie_providers": {
            "10musume": "https://www.10musume.com/",
            "1Pondo": "https://www.1pondo.tv/",
            "AIRAV": "https://www.airav.wiki/",
            "ARZON": "https://www.arzon.jp/",
            "AVBASE": "https://www.avbase.net/",
            "AVE": "https://www.aventertainments.com/",
            "C0930": "https://www.c0930.com/",
            "Caribbeancom": "https://www.caribbeancom.com/",
            "CaribbeancomPR": "https://www.caribbeancompr.com/",
            "DAHLIA": "https://dahlia-av.jp/",
            "DUGA": "https://duga.jp/",
            "FALENO": "https://faleno.jp/top/",
            "FANZA": "https://www.dmm.co.jp/",
            "FC2": "https://adult.contents.fc2.com/",
            "Gcolle": "https://gcolle.net/",
            "Getchu": "https://dl.getchu.com/",
            "H0930": "https://www.h0930.com/",
            "H4610": "https://www.h4610.com/",
            "HEYZO": "https://www.heyzo.com/",
            "HeyDouga": "https://www.heydouga.com/",
            "JAV321": "https://www.jav321.com/",
            "JavBus": "https://www.javbus.com/",
            "KIN8": "https://www.kin8tengoku.com/",
            "MGS": "https://www.mgstage.com/",
            "MURAMURA": "https://www.muramura.tv/",
            "MYWIFE": "https://mywife.cc/",
            "PACOPACOMAMA": "https://www.pacopacomama.com/",
            "Pcolle": "https://www.pcolle.com/",
            "SOD": "https://ec.sod.co.jp/prime/",
            "TOKYO-HOT": "https://my.tokyo-hot.com/",
            "XXX-AV": "https://www.xxx-av.com/",
            "fc2hub": "https://javten.com/"
        }
    }
}

### How to Reproduce

docker一下就复现了，我看到有很多被关掉的没有提供有效信息的issue也提到过国产没刮削成功

**Comment by Not-a-good-username** [comment]
感觉这个好像不算是插件的问题，应该是server那边的问题，但是感觉那边有点冷清，就先放这里了，如果说不合适就去那边也行~

**Comment by xjasonlyu** [comment]
是的，没有把国产默认加进来，因为感觉不是很适配暂时。

**Comment by Not-a-good-username** [comment]
懂了，礼貌问下短期内有加入计划吗，如果有的话我就敬候佳音，没有的话我就先把国产相关资源移出媒体库，看着闹心hhhhhhhhhhh。

顺便问下现在有看到标题简介和评论的翻译，会考虑加入标签翻译嘛

**Comment by xjasonlyu** [comment]
暂时没有，因为我计划是把他们分开，有专门的日本，欧美，国产三个插件，共用一个后端这么打算。所以无论如何都是要区分媒体库的我感觉。

**Comment by Not-a-good-username** [comment]
好的，收到！反正实际存储位置我是分开的，所以应该还好，移除一个文件夹配置而已，期待大佬最新力作（bushi）

**Comment by Bennie-CHEN** [comment]
期待
