### ISSUE TITLE
[Bug] 添加仓库后，插件库里没有

### ISSUE THREAD

**Issue by yzlyu** [metatube-community/jellyfin-plugin-metatube#87]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

——

### JavTube Server Version

——

### What OS are you seeing the problem on?

Linux

### Description

群辉套件版jellyfin，添加仓库链接（https://raw.githubusercontent.com/javtube/jellyfin-plugin-javtube/dist/manifest.json）后，在插件列表里无javtube。

### JavTube Server

——

### Jellyfin/Emby Logs

——

### JavTube Server Logs

——

### How to Reproduce

——

**Comment by yzlyu** [comment]
使用docker 安装jellyfin后，安装插件后显示 notsupport 

![111](https://user-images.githubusercontent.com/9254175/201471976-8892e642-6633-42bf-93b0-690c4283cde3.png)

**Comment by hwadong860** [comment]
请仔细看一遍wiki。
Jellyfin 版本要10.8.x
![image](https://user-images.githubusercontent.com/56748901/202132897-623bc8e0-97c0-41bb-9279-1f438f4d1323.png)

**Comment by yzlyu** [comment]
> 请仔细看一遍wiki。 Jellyfin 版本要10.8.x ![image](https://user-images.githubusercontent.com/56748901/202132897-623bc8e0-97c0-41bb-9279-1f438f4d1323.png)

感觉大佬回复，因群辉套件版本是10.7x 所以我特意用docker装了10.8，结果显示notsupport，如上楼回复。之前未描述情况，抱歉。
