### ISSUE TITLE
[Bug] 服务器刮削后无法将nfo及图片数据保存在视频同级目录

### ISSUE THREAD

**Issue by heizcode** [metatube-community/jellyfin-plugin-metatube#88]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.1102.520.0

### JavTube Server Version

1.0.22

### What OS are you seeing the problem on?

Windows

### Description

在Windows环境下的Emby服务器刮削后无法将nfo及图片数据保存在视频同级目录，麻烦帮忙看看谢谢

**Comment by xjasonlyu** [comment]
没有这个问题，你看看是不是权限没给对。

**Comment by heizcode** [comment]
> 没有这个问题，你看看是不是权限没给对。

已处理麻烦您了，是挂载的路劲需要管理权限才能进行操作，用管理员身份运行emby服务器即可
