### ISSUE TITLE
[Bug] 刮削源数据只有Arzon源数据

### ISSUE THREAD

**Issue by heizcode** [metatube-community/jellyfin-plugin-metatube#89]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.1102.520.0

### JavTube Server Version

1.0.22

### Description

Windows环境直接运行后端exe部署，在Emby刮削数据的时候会出现刮削的数据只有”Arzon源数据“，具体错位未定位

暂时解决办法：避免使用EXE方式运行后端，转用Widows部署Docker环境运行后端

**Comment by xjasonlyu** [comment]
我猜是网络问题。
