### ISSUE TITLE
[Bug] 新版本刮削导致后端服务器宕机

### ISSUE THREAD

**Issue by hwadong860** [metatube-community/jellyfin-plugin-metatube#91]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.1102.520.0

### JavTube Server Version

1.0.22

### What OS are you seeing the problem on?

Linux

### Description

就只有我有这个我问题吗？
服务端安装在VPS上，资源只有1核1G，更新了1.0.22新版本服务后端后，刮削的时候会把服务器资源拉满，然后导致服务器宕机无响应。

![1](https://user-images.githubusercontent.com/56748901/202110742-f2f261a7-0556-49d5-8c88-02195168dea3.jpg)
![2](https://user-images.githubusercontent.com/56748901/202110834-1d3016d4-47d9-4ada-b1d3-009829c2e4c1.jpg)
![3](https://user-images.githubusercontent.com/56748901/202110775-d094a9ea-2bb1-4f3c-9ae6-ba3eec116cbc.png)

### JavTube Server

No response

### Jellyfin/Emby Logs

No response

### JavTube Server Logs

No response

**Comment by xjasonlyu** [comment]
这应该是你VPS的问题，内存太小所以OOM了。

**Comment by hwadong860** [comment]
vps内存是小了… 
看监控是CPU先被拉满了，这正常吗？

**Comment by xjasonlyu** [comment]
正常的，刮削起来要做各种图片运算和图像处理，是比较占CPU的。

**Comment by hwadong860** [comment]
虽然没留意，但是印象中旧版本CPU没有现在这样高，跑起来也不会宕机。
像这样情况的话，放在大多数VPS实例上都运行不了呢…希望大佬能优化下啊。
