### ISSUE TITLE
[Bug]docker容器启动失败 

### ISSUE THREAD

**Issue by albicoccca** [metatube-community/jellyfin-plugin-metatube#94]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.1102.520.0

### JavTube Server Version

1.0.22

### What OS are you seeing the problem on?

Linux

### Description

docker部署后端，首次运行正常，但是javtube.db文件一直没有生成。
之后启动就不停报错，看起来是数据库的问题，一直这几句循环，不知道问题原因是什么。

### JavTube Server

compose配置如下： 

 javtube:
    image: javtube/javtube-server:latest
    container_name: javtube
    environment:
      - DSN= /config/javtube.db
      - TZ=${tz}
    volumes:
      - ${docker}javtube:/config
    ports:
      - 9184:8080
    restart: unless-stopped

### JavTube Server Logs

2022/11/24 16:01:25 unable to open database file: out of memory (14)
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:02:25 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:02:25 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:03:25 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:03:25 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:04:26 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:04:26 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:05:26 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:05:26 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:06:27 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:06:27 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:07:27 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:07:27 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:08:28 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:08:28 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:09:28 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:09:28 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:10:29 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:10:29 unable to open database file: out of memory (14)
2022/11/24 16:11:29 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:11:29 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:12:29 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:12:29 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:13:30 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:13:30 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:14:30 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:14:30 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:15:31 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:15:31 unable to open database file: out of memory (14)
2022/11/24 16:16:31 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:16:31 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:17:31 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:17:31 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:18:32 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:18:32 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:19:32 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:19:32 unable to open database file: out of memory (14)
[GORM] 2022/11/24 16:20:32 gorm.io/gorm@v1.24.1/gorm.go:206
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2022/11/24 16:20:32 unable to open database file: out of memory (14)

**Comment by QZQ-QSQ** [comment]
你安装后端的地方（硬盘/闪存？）不够容量空间放数据文件了，换个安装路径吧，应该就可以了。

**Comment by albicoccca** [comment]
> 你安装后端的地方（硬盘/闪存？）不够容量空间放数据文件了，换个安装路径吧，应该就可以了。

系统抽风，日志文件把硬盘占满了，看英文提示还一直想着是内存的问题。。。
现在还有点小问题，不过基本是能用了
